### ISSUE TITLE
[Bug]: Error: listen EADDRINUSE: address already in use :::

### ISSUE THREAD

**Issue by amery78** [homebridge-eufy-security/plugin#138]
### What happened?

Hello, after updating to latest RC I have a bug in Dufy Plugin.
I've updated to RC then to Beta but same issue.
The reason why I've updated is because in the last stable release I had the automatic backup bug with homebridge.

The plugin is restarting in loop again and again since I updated it.

Homebridge version : 1.5.0

Thank you in advance for your help :)

### Device Type

other (UnSupported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[8/11/2022, 1:27:01 PM] [homebridge-eufy-security] Child bridge process ended
[8/11/2022, 1:27:01 PM] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
[8/11/2022, 1:27:08 PM] [homebridge-eufy-security] Restarting Process...
[8/11/2022, 1:27:09 PM] [homebridge-eufy-security] Launched child bridge with PID XXXXXXX
[8/11/2022, 1:27:10 PM] Registering platform 'homebridge-eufy-security.EufySecurity'
[8/11/2022, 1:27:10 PM] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.2.0-beta.1 child bridge successfully
[8/11/2022, 1:27:10 PM] Loaded 11 cached accessories from cachedAccessories.XXXXXXXXX.
[8/11/2022, 1:27:10 PM] [EufySecurity-2.2.0-beta.1] WARN:  warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[8/11/2022, 1:27:10 PM] [EufySecurity-2.2.0-beta.1] INFO:  Country set: FR
[8/11/2022, 1:27:10 PM] [EufySecurity-2.2.0-beta.1] INFO:  Finished initializing!
Error: listen EADDRINUSE: address already in use ::: XXXXXXX
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:332:21)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:18)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
[8/11/2022, 1:27:10 PM] [homebridge-eufy-security] Child bridge process ended
```

**Comment by thieren** [comment]
Hey @amery78 

This should not be an error of the plugin.

As far as I know this means that the homebridge instance did not release it's port orderly.

One way to mitigate this should be to restart the computer that homebridge runs on.

**Comment by amery78** [comment]
It works !
Thank you :)

Axel Mery
