### ISSUE TITLE
[Bug]: Cannot Backup Homebridge

### ISSUE THREAD

**Issue by vskal** [homebridge-eufy-security/plugin#163]
### What happened?

A bug happened! I cannot backup my Homebridge anymore ! 

I get the following error:

[Homebridge UI] Backup failed, removing /tmp/homebridge-backup-oeDmBO
Error: Cannot copy a socket file: /homebridge/eufysecurity/8.sock
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/fs-extra/lib/copy/copy.js:78:44
    at callback (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:199:5)
[Homebridge UI] Backup Failed Error: Cannot copy a socket file: /homebridge/eufysecurity/8.sock

I read that I should update the homebridge-eufy-security plugin to RC since it doesn’t use the socket files anymore, then delete the socket files from the directory.

Is this a solution ? Any tips for a NAS container installation please  ?

### Device Type

Indoor Camera (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Windows 10+ (Supported)

### Relevant log output

```shell
[Homebridge UI] Backup failed, removing /tmp/homebridge-backup-oeDmBO
Error: Cannot copy a socket file: /homebridge/eufysecurity/8.sock
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/fs-extra/lib/copy/copy.js:78:44
    at callback (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:199:5)
[Homebridge UI] Backup Failed Error: Cannot copy a socket file: /homebridge/eufysecurity/8.sock
```

### config

```shell
{
            "enableDetailedLogging": 0,
            "hkOff": 63,
            "platform": "EufySecurity",
            "username": "xxxxxxxxxxxxxxxxxx",
            "pollingIntervalMinutes": 5,
            "hkHome": 1,
            "password": "xxxxxxxxxxxxxxx",
            "enableCamera": true,
            "hkNight": 47,
            "ignoreStations": [
                ""
            ],
            "hkAway": 0,
            "ignoreDevices": [
                ""
            ],
            "cleanCache": true,
            "country": "xx"
        },
```

**Comment by thieren** [comment]
Hi @vskal 

I also would recommend to update to the latest version and delete the socket file manually.

**Comment by vskal** [comment]
Hi @thieren and many thanks for the reply.

I tried the suggested solution but I cannot delete the sock files (even when the container is down), I get file access is denied.

I also uninstalled the plugin but still cannot delete the sock files. I am quite frustrated on how to get backups working again.

**Comment by thieren** [comment]
I can understand your frustration and I'll try helping you out here.

Have you tried to remove the files with root permissions aka `sudo`? Also it might help if you restart the whole system, since there might be an ipc-process stuck which prevents deletion of that file.

**Comment by vskal** [comment]
Thank you for your understanding and for helping me out on this !

I have just rebooted the QNQP NAS in case an -ipc process is stuck. Tried a Homebridge Backup but I got the above 8.sock error. 

I then stopped the container and tried to delete a socket file (using QNAP's File station app) but the it failed to delete it (failed to access the file).
I also checked the permissions for the folder and they are allowed on the admin account.

I should note that In the NAS priviledges section, the Container folder has a note stating: "This shared folder is for container station and cannot be changed or removed". It seems that in my case, it is not straight forward to work with files in containers.

On your question regarding the sudo command, I have not tried it, I am afraid I do not have the experience on how to do it  but I can follow instructions.

**Comment by thieren** [comment]
I am not really accustomed to qnap nas systems, but since this should be a linux system I think we can work something out.

First please enable ssh access to your nas (https://www.qnap.com/en/how-to/faq/article/how-do-i-access-my-qnap-nas-using-ssh). You can disable it again after we're done.

Follow the instructions to connect to your nas via a terminal and run just the command `id`. If you post the output here I can see if the logged in user is already root and we can continue from there.

**Comment by vskal** [comment]
Yes, this is the response to id

uid=1002(Admin name) gid=100(everyone) groups=0(administrators),100(everyone)

**Comment by thieren** [comment]
Ok, the root uid would be 0 but it might just be enough that the user it member of the group 0.

As far as I could learn from the net there is no `sudo` command on the standard qnap system. You would have to install it manually, but we'll try without it first.

Do you now your way around the terminal? you would have to find the homebridge directory with the eufysecurity folder inside it. in there is the 8.sock file you want to remove.
After changing into this directory you can try this with `rm -f 8.sock` or if it is somehow on your system you can try `sudo rm -f 8.sock`

**Comment by thieren** [comment]
No Problem. Glad it could be solved for you!

**Comment by saltysmith1** [comment]
sorry for reopening this, i have been facing this issue too,

im currently running beta v 2.2.0 beta 5 this is running on a virtual windows machine with homebridge v 4.50.1 not completely sure how i go about removing the .8 sock file, any help would be very very much appreciated
