### ISSUE TITLE
[Bug]: Error: listen EADDRINUSE: address already in use :::44119

### ISSUE THREAD

**Issue by fleiscpj** [homebridge-eufy-security/plugin#178]
### What happened?

Using the HomeBridge package on a Synology DS920+.  Plugin runs on initial start.  If homebridge is restarted the following error occurs.  This error occurs with 2.1.0 and 2.2.0-beta5.  Running Homebridge 1.5

Error: listen EADDRINUSE: address already in use :::44119
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at EventedHTTPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:332:21)
    at Bridge.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:18)
    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)

### Device Type

other (UnSupported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
Error: listen EADDRINUSE: address already in use :::44119
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at EventedHTTPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:332:21)
    at Bridge.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:18)
    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
```

### config

```shell
{
            "platform": "EufySecurity",
            "username": "",
            "password": "",
            "ignoreStations": [
                ""
            ],
            "ignoreDevices": [
                ""
            ],
            "_bridge": {
                "username": "",
                "port": 44119
            },
            "enableCamera": true,
            "pollingIntervalMinutes": 30,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": 0,
            "country": "US",
            "cameras": [
                {
                    "serialNumber": "S1",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": true,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "useEnhancedSnapshotBehaviour": true,
                    "snapshotHandlingMethod": 3,
                    "immediateRingNotificationWithoutSnapshot": true,
                    "delayCameraSnapshot": false,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "S2",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": true,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "useEnhancedSnapshotBehaviour": true,
                    "snapshotHandlingMethod": 3,
                    "immediateRingNotificationWithoutSnapshot": false,
                    "delayCameraSnapshot": false,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "S3",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": true,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "useEnhancedSnapshotBehaviour": true,
                    "snapshotHandlingMethod": 1,
                    "immediateRingNotificationWithoutSnapshot": false,
                    "delayCameraSnapshot": false,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "S4",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": true,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "useEnhancedSnapshotBehaviour": true,
                    "snapshotHandlingMethod": 3,
                    "immediateRingNotificationWithoutSnapshot": false,
                    "delayCameraSnapshot": false,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "S5",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": true,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "useEnhancedSnapshotBehaviour": true,
                    "snapshotHandlingMethod": 3,
                    "immediateRingNotificationWithoutSnapshot": false,
                    "delayCameraSnapshot": false,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "S6",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": true,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "useEnhancedSnapshotBehaviour": true,
                    "snapshotHandlingMethod": 3,
                    "immediateRingNotificationWithoutSnapshot": false,
                    "delayCameraSnapshot": false,
                    "videoConfig": {
                        "audio": true
                    }
                }
            ],
            "cleanCache": true
        },
```

**Comment by fleiscpj** [comment]
Yes

**Comment by thieren** [comment]
Hi @fleiscpj 

this seems to be a homebridge issue and not related to this plugin. Usually you can workaround this by restarting the system (so in this case the sinology itself) but if this happens every time you restarted then I'd recommend to open an issue in the homebridge repo.

The error itself refers to a port that is not released properly on shutdown. Why this is I can't say since this is, as said, not related to this plugin.

**Comment by gmogoody** [comment]
I resolved this issue by restarting my Homebridge container. It’s not related to this plugin as others have posted.
