### ISSUE TITLE
[Bug]: Devices not loading

### ISSUE THREAD

**Issue by timmy8784** [homebridge-eufy-security/plugin#215]
### What happened?

Updated to version 2.1.2 and no devices will show even though show in plug in settings. Reverted back to version 2.1.0 but will not allow login. Child bridge adds but no devices will setup. Also noticed device name under eufy login. What is this used for?

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[16/11/2022, 16:19:28] Registering platform 'homebridge-eufy-security. Eufysecurity' [16/11/2022, 16:19:28] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.1.2 child bridge successfully
[16/11/2022, 16:19:28] Loaded 0 cached accessories from cachedAccessories. OECE531A730B.
[11/16/2022,
4:19:28 PM] [EufySecurity-2.1.2] WARN :
warning: planned changes, see https:
//github.com/homebridge-eufy-security/plugin/issues /1
[11/16/2022, 4:19:28 PM [EufySecurity-2.1.2] INFO:
Country set: US
[11/16/2022, 4:19:28 PM] [EufySecurity-2.1.2] INFO:
Finished initializing!
[16/11/2022, 16:19:28] Homebridge v1.5.0 (HAP v0.10.4) (homebridge-eufy-security) is runn ing on port 58747.
```

### config

```shell
,
        {
            "platform": "EufySecurity",
            "ignoreStations": [],
            "ignoreDevices": [],
            "cleanCache": true,
            "_bridge": {
                "username": "0E:CE:53:1A:73:0B",
                "port": 58747
            }
        }
```

**Comment by schliemann** [comment]
DeviceName is a required property in the new version of the eufy security client. Without it login wouldn't work anymore.

**Comment by schliemann** [comment]
Which country are your devices added in?

**Comment by timmy8784** [comment]
The devices are in USOn Nov 17, 2022, at 12:08 PM, schliemann ***@***.***> wrote:﻿
Which country are your devices added in?

**Comment by timmy8784** [comment]
What do you put in this field?On Nov 17, 2022, at 12:07 PM, schliemann ***@***.***> wrote:﻿
DeviceName is a required property in the new version of the eufy security client. Without it login wouldn't work anymore.

**Comment by schliemann** [comment]
You don't have to give it a value. If it is empty it will write MyPhone. It just needs a value since it is a requirement forced by Eufy.

**Comment by timmy8784** [comment]
> You don't have to give it a value. If it is empty it will write MyPhone. It just needs a value since it is a requirement forced by Eufy.

I just tried again. I did my login and put MyEufy in the device name. It takes me to the captcha screen but when i enter and click verify, it gives me a never ending spinning wheel. 

However when I exit out and go back into the plug-in settings, it shows my devices under my account, but no devices show in HomeKit or homebridge

**Comment by timmy8784** [comment]
i upgraded to version 2.1.3 and still have the same issue.  I can get to the captcha screen, but spins on verify.  When i restart, this is what i see in the log even though i can see my devices when i go to plugin settings

[17/11/2022, 13:51:26] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge 314C) is running on port 51976.
[11/17/2022, 1:51:27 PM] [EufySecurity-2.1.3] ERROR: Not connected can't continue!

**Comment by timmy8784** [comment]
if it helps, here is the log when i try to enter my login information

[17/11/2022, 14:01:51] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[17/11/2022, 14:01:51] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[17/11/2022, 14:02:03] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[17/11/2022, 14:02:12] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[17/11/2022, 14:02:24] [Homebridge UI] [homebridge-eufy-security] /var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/station.js:107
            this.rawStation.params.forEach(param => {
                                   ^

TypeError: Cannot read properties of null (reading 'forEach')
    at Station.update (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/station.js:107:36)
    at new Station (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/station.js:62:14)
    at Station.initialize (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/station.js:73:25)
    at EufySecurity.handleHubs (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/eufysecurity.js:360:51)
    at HTTPApi.<anonymous> (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/eufysecurity.js:126:44)
    at HTTPApi.emit (node:events:513:28)
    at HTTPApi.refreshStationData (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/api.js:518:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPApi.refreshAllData (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/api.js:543:9)
    at async EufySecurity.refreshCloudData (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/eufysecurity.js:565:9)

Node.js v18.12.1

**Comment by schliemann** [comment]
Looks like an error originating from the Eufy Security Client. You should try and create an issue on Bropats repo.

**Comment by timmy8784** [comment]
> Looks like an error originating from the Eufy Security Client. You should try and create an issue on Bropats repo.

Guessing you mean the bropats eufy security client GitHub?

**Comment by schliemann** [comment]
> > Looks like an error originating from the Eufy Security Client. You should try and create an issue on Bropats repo.
> 
> Guessing you mean the bropats eufy security client GitHub?

Yeah.

**Comment by timmy8784** [comment]
> > > Looks like an error originating from the Eufy Security Client. You should try and create an issue on Bropats repo.
> 
> > 
> 
> > Guessing you mean the bropats eufy security client GitHub?
> 
> 
> 
> Yeah.

Cool, I just submitted the issue there and hopefully someone can help. Thanks!

**Comment by thieren** [comment]
To better follow the progress I'll link the issue here: https://github.com/bropat/eufy-security-client/issues/250

**Comment by timmy8784** [comment]
Any update on this?

**Comment by adarshk23** [comment]
I can successfully log in but it takes me to the 'Devices loading' prompt which stays forever.
<img width="591" alt="Screenshot 2022-12-21 at 9 10 54 pm" src="https://user-images.githubusercontent.com/102000816/208879950-26d58650-f903-4840-9f2d-5f24ad698caf.png">

**Comment by timmy8784** [comment]
I am having the exact same problem. None of my accessories were functioning and tried to reset everything. Now when I login i get the same issue and can get nothing back. Plug-in was working fine a few days ago

**Comment by thieren** [comment]
Hi folks,

eufy just changed some things with their servers again. Look here for the appropriate issue: https://github.com/homebridge-eufy-security/plugin/issues/250
