### ISSUE TITLE
[Bug]: Bunyan dependency error: "rotating-file" stream type is not supported

### ISSUE THREAD

**Issue by rmcampen** [homebridge-eufy-security/plugin#230]
### What happened?

New to this plugin and not great with programming. I can't seem to launch the plugin at all.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[11/27/2022, 2:04:31 PM] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.1.3 child bridge successfully

/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:607
        assert.ok(mv, '"rotating-file" stream type is not supported: '
               ^
AssertionError [ERR_ASSERTION]: "rotating-file" stream type is not supported: missing "mv" module
    at Logger.addStream (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:607:16)
    at /usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:470:18
    at Array.forEach (<anonymous>)
    at new Logger (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:469:25)
    at Function.createLogger (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:1620:12)
    at new EufySecurityPlatform (/usr/local/lib/node_modules/homebridge-eufy-security/src/plugin/platform.ts:109:23)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:150:42)
[11/27/2022, 2:04:31 PM] [homebridge-eufy-security] Child bridge process ended
[11/27/2022, 2:04:31 PM] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
```

### config

```shell
{
            "platform": "EufySecurity",
            "username": "***",
            "password": "***",
            "pollingIntervalMinutes": 30,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": false,
            "country": "US",
            "CameraMaxLivestreamDuration": 30,
            "cleanCache": true,
            "ignoreStations": [
                "T8010T1522180924",
                "T8203P112230015C"
            ],
            "ignoreDevices": [
                "T8142T93221725CF",
                "T8142T932217390D",
                "T8142T932217252B",
                "T8142T5322260AB5"
            ],
            "_bridge": {
                "username": "***",
                "port": 50202
            }
        },
        {
```

**Comment by thieren** [comment]
Hi @rmcampen 

It seems that your installation of the dependencies didn't work properly. How did you install homebridge and this plugin?

**Comment by rmcampen** [comment]
> Hi @rmcampen
> 
> It seems that your installation of the dependencies didn't work properly. How did you install homebridge and this plugin?

Hi, sorry for the delay in response. It’s been awhile since I installed Homebridge, but if I recalled correctly,I did so via the sudo command. I installed the plug-in via the Homebridge UI.

**Comment by thieren** [comment]
That's strange. I'd like you to check if there is an update to `node` available on the system running homebridge.
Also please try to uninstall and reinstall the plugin. Maybe npm did something wrong while installing.

**Comment by rmcampen** [comment]
My apologies, @thieren. I have a three and a half year old and a seven week old and life unfortunately takes me away from my smart home hobby more than I wish. I appreciate your help. Might just be a little while between responses.

It looks like I'm running node 16.5.1 and I cannot update any further on my system due to the age of my Mac. I am considering either a Pi or a new Mac in 2023 (and would run my Homebridge instance off of either said Pi or the current Mac I'm using (which if I recall correctly is a 2015 model).

As for reinstalling the plugin, I've done that as well. It looks like it installs, but the gear just keeps spinning on the settings page. When I quit out and go back to the log, it shows me the same error as before:

[12/17/2022, 10:15:05 AM] [Homebridge UI] [homebridge-eufy-security] node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: "rotating-file" stream type is not supported: missing "mv" module
    at Logger.addStream (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:607:16)
    at /usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:470:18
    at Array.forEach (<anonymous>)
    at new Logger (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:469:25)
    at Function.createLogger (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/bunyan/lib/bunyan.js:1620:12)
    at new UiServer (/usr/local/lib/node_modules/homebridge-eufy-security/homebridge-ui/server.js:22:37)
    at /usr/local/lib/node_modules/homebridge-eufy-security/homebridge-ui/server.js:302:12
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/homebridge-ui/server.js:303:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}

**Comment by thieren** [comment]
> My apologies, @thieren. I have a three and a half year old and a seven week old and life unfortunately takes me away from my smart home hobby more than I wish. I appreciate your help. Might just be a little while between responses.

Absolutely no need to apologise. I know your troubles. ;-)

> It looks like I'm running node 16.5.1

You most likely mean `16.15.1`, right? That should be the latest I think.

Apart from that I don't really know if I can help here since the error seems to be caused by a dependency. And since nobody else so far reported a similar issue I'm guessing it has something to do with your individual setup.
Maybe reinstalling homebridge with updated versions of node, npm, etc. will do the trick. Other than that another system will most likely also do the trick I think.
