### ISSUE TITLE
Smart lock T8510 ignored but still crashing homebridge

### ISSUE THREAD

**Issue by frogking1012** [homebridge-eufy-security/plugin#233]
### What happened?

The script crashes every time it tries to load Bluetooth smart lock T8510, which is in my eufy account. I understand it is not supported, I select to ignore this device in settings. But it still fails.

### Device Type

other (UnSupported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[11/28/2022, 10:32:36 PM] [EufySecurity-2.1.3] DEBUG: Found device T8510Q10212503B0 Front Door Lock LOCK_BLE [11/28/2022, 10:32:36 PM] [EufySecurity-2.1.3] DEBUG: Device ignored [11/28/2022, 10:32:37 PM] TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined at new NodeError (node:internal/errors:372:5) at Function.from (node:buffer:323:9) at stringWithLength (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/utils.ts:28:35) at p2pDidToBuffer (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/utils.ts:56:18) at buildCheckCamPayload (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/utils.ts:108:26) at P2PClientProtocol.sendCamCheck (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:429:45) at P2PClientProtocol._connect (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:380:18) at P2PClientProtocol.handleMsg (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:698:22) at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:119:56) at Socket.emit (node:events:527:28)
```

### config

```shell
Na
```

**Comment by thieren** [comment]
Hi @frogking1012 

the error seems to be caused by [eufy-security-client](https://github.com/bropat/eufy-security-client) which is used by this plugin to establish the connection to the eufy cloud. Maybe we'll have to open an issue in this repo.

Can you supply the full logs `eufy-log.log` and `log-lib.log` files for this error? Then maybe I could have a look.

Maybe a workaround to try:
You're supposed to use a guest account for this plugin and not your main eufy account. As far as I know you should be able to define which devices should be shared with this guest account. So if you don't share the lock with your guest account, the plugin should not see this device in the first place.

**Comment by frogking1012** [comment]
[log-lib.log](https://github.com/homebridge-eufy-security/plugin/files/10111268/log-lib.log)

**Comment by frogking1012** [comment]
[eufy-log.log.zip](https://github.com/homebridge-eufy-security/plugin/files/10111311/eufy-log.log.zip)

**Comment by frogking1012** [comment]
Thx @thieren. I have uploaded the two files and will try the workaround.

**Comment by frogking1012** [comment]
just an update, the workaround works!

**Comment by thieren** [comment]
> just an update, the workaround works!

Thx for the feedback. Will have a look at the log files later.

**Comment by thieren** [comment]
Hi @frogking1012 

I can't see exactly what is causing this. I'd recommend opening a feature request at [eufy-security-client](https://github.com/bropat/eufy-security-client) to get the support for the smart lock. Bropat will most likely ask you to share the device so that he can implement the needed features.

Since we do have a workaround, I'll close this issue for this plugin.
