### ISSUE TITLE
[Bug]: error when using Homebridge UI to restart, workaround is restart the container outside of Homebridge UI

### ISSUE THREAD

**Issue by DolmensDude** [homebridge-eufy-security/plugin#289]
### What happened?

when using Homebridge UI to restart, this happens, and never resolves on its own, it just cycles through restart loop.

Error: listen EADDRINUSE: address already in use :::56382
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
 =========================================================   
However, restarting the container itself works fine. 
    
This showed up now and then before all of the login changes a couple of weeks back, but now is repeatable every time.

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
Error: listen EADDRINUSE: address already in use :::56382
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
```

### config

```shell
{
            "platform": "EufySecurity",
            "username": "*********************",
            "password": "*********************",
            "country": "NL",
            "ignoreStations": [],
            "ignoreDevices": [],
            "cameras": [
                {
                    "serialNumber": "*********************",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": false,
                    "unbridge": false,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    },
                    "talkback": true,
                    "useEnhancedSnapshotBehaviour": true,
                    "snapshotHandlingMethod": 2,
                    "hsv": true,
                    "refreshSnapshotIntervalMinutes": 0,
                    "delayCameraSnapshot": true
                },
                {
                    "serialNumber": "*********************",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": false,
                    "unbridge": false,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    },
                    "talkback": true,
                    "snapshotHandlingMethod": 2,
                    "hsv": true,
                    "refreshSnapshotIntervalMinutes": 0,
                    "delayCameraSnapshot": true
                },
                {
                    "serialNumber": "*********************",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": false,
                    "unbridge": false,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    },
                    "talkback": true,
                    "snapshotHandlingMethod": 3,
                    "immediateRingNotificationWithoutSnapshot": true,
                    "delayCameraSnapshot": true,
                    "hsv": false,
                    "hsvRecordingDuration": 90,
                    "hsvConfig": {}
                },
                {
                    "serialNumber": "*********************",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": false,
                    "unbridge": false,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    },
                    "talkback": true,
                    "snapshotHandlingMethod": 3,
                    "immediateRingNotificationWithoutSnapshot": true,
                    "delayCameraSnapshot": true,
                    "hsv": false,
                    "refreshSnapshotIntervalMinutes": 0,
                    "hsvRecordingDuration": 90,
                    "hsvConfig": {}
                },
                {
                    "serialNumber": "*********************",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "*********************",
                    "enableCamera": "true",
                    "videoConfig": {
                        "audio": true
                    },
                    "talkback": true,
                    "hsv": true,
                    "snapshotHandlingMethod": 2,
                    "refreshSnapshotIntervalMinutes": 0,
                    "delayCameraSnapshot": true
                },
                {
                    "serialNumber": "*********************",
                    "enableCamera": "true",
                    "videoConfig": {
                        "audio": true
                    },
                    "talkback": true,
                    "hsv": true,
                    "snapshotHandlingMethod": 2,
                    "refreshSnapshotIntervalMinutes": 0,
                    "delayCameraSnapshot": true
                }
            ],
            "cleanCache": true,
            "CameraMaxLivestreamDuration": 120,
            "deviceName": "Eufy",
            "_bridge": {
                "username": “*********************”,
                "port": 56382
            }
        },
```

**Comment by drew-hill** [comment]
Same.

**Comment by baraoresmungao** [comment]
Just started having preciselly the same error. No changes on the system, it just started.... any idea of what might be the issue?

**Comment by lenoxys** [comment]
can you update to 2.2.5 and enable troubleshooting ? 
https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting

**Comment by baraoresmungao** [comment]
Logs
[fd1901d9-b50a-4c93-9ed6-010c72d80f4e.zip](https://github.com/homebridge-eufy-security/plugin/files/12428850/fd1901d9-b50a-4c93-9ed6-010c72d80f4e.zip)

**Comment by lenoxys** [comment]
do you have persistent.json file into Eufy Directory ?

**Comment by baraoresmungao** [comment]
Attached persistent.json

**Comment by baraoresmungao** [comment]
I’ve deleted all cached equipment in homebridge and it sorted the problem.

**Comment by lenoxys** [comment]
Thanks for your feedback! I'm closing the case !

**Comment by elder-cb** [comment]
I've just had what looks like the same issue: restarting homebridge from the UI, or even just the child bridge eufy is running in, would fail to start this plugin complaining about address in use (child bridge running on port 45414 in my case).
I connected via ssh to the RasPI4 running homebridge and I could see a few connections in CLOSE_WAIT on that port, nothing listening on it.
```
pi@homebridge:~ $ netstat -t t |grep 45414
tcp6     184      0 homebridge.fritz.:45414 192.168.4.65:61447      CLOSE_WAIT
tcp6     194      0 homebridge.fritz.:45414 homebridge.fritz.:51846 CLOSE_WAIT
tcp6     194      0 homebridge.fritz.:45414 homebridge.fritz.:39344 CLOSE_WAIT
tcp6     194      0 homebridge.fritz.:45414 homebridge.fritz.:57594 CLOSE_WAIT
tcp6     194      0 homebridge.fritz.:45414 homebridge.fritz.:44748 CLOSE_WAIT
```
I tried clearing cached accessories, but that did not solve the issue.
I've rebooted the RasPI and it's not started correctly again :/

Running with
- Homebridge v1.7.0
- Node.js Version v20.11.0
- homebridge-eufy-security v2.3.22

**Comment by lenoxys** [comment]
Hello, is this related to this error in logs `Error: listen EADDRINUSE: address already in use :::56382`

If yes, please stop the plugin for 30min and retry.
