### ISSUE TITLE
Doorbells no longer visible in HomeBridge

### ISSUE THREAD

**Issue by thecolinscott** [homebridge-eufy-security/plugin#331]
### What happened?

A bug happened!  I have 3 doorbells connected by HomeBridge.  They have run satisfactorily for months.  Today they just dropped off my Home's device list.  On checking Homebridge, they have also dropped off the Homebridge device lists. The relevant parts of the log seem to indicate that the plugin has been unable to login to the Eufy Security site, although I am able to login from a browser using the configured credentials (although I have redacted the credentials below).

I am running Homebridge on a Synology NAS running DSM 7.1.1-42962 Update 5

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
[6/12/2023, 9:55:30 PM] [EufySecurity-2.1.7] ERROR: Error while setup :  RequestError: getaddrinfo EAI_AGAIN extend.eufylife.com
    at ClientRequest.<anonymous> (/volume1/homebridge/node_modules/homebridge-eufy-security/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/volume1/homebridge/node_modules/homebridge-eufy-security/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  code: 'EAI_AGAIN',
  timings: {
    start: 1686603320025,
    socket: 1686603320026,
    lookup: 1686603330034,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1686603330041,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 10008,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10016
    }
  }
}
[6/12/2023, 9:55:30 PM] [EufySecurity-2.1.7] ERROR: Not connected can't continue!
```

### config

```shell
{
    "username": "UUUUUUUUUUUUUUUUUUUU",
    "password": "PPPPPPPPPPPPPPPPPPP",
    "country": "GB",
    "platform": "EufySecurity",
    "cameras": [
        {
            "serialNumber": "T8210P6422033932",
            "rtsp": false,
            "enableCamera": true,
            "immediateRingNotificationWithoutSnapshot": true,
            "talkback": true,
            "videoConfig": {
                "audio": true,
                "audioSampleRate": 0
            }
        },
        {
            "serialNumber": "T8200N0021121ECA",
            "rtsp": false,
            "enableCamera": true,
            "immediateRingNotificationWithoutSnapshot": true,
            "videoConfig": {
                "audio": true,
                "audioSampleRate": 0
            },
            "talkback": true
        },
        {
            "serialNumber": "T8210P64220335ED",
            "rtsp": false,
            "enableCamera": true,
            "immediateRingNotificationWithoutSnapshot": true,
            "videoConfig": {
                "audio": false,
                "audioSampleRate": 0
            },
            "talkback": false
        }
    ],
    "stations": [
        {
            "serialNumber": "T8200N0021121ECA",
            "manualTriggerModes": []
        }
    ],
    "ignoreStations": [],
    "ignoreDevices": [],
    "cleanCache": true
}
```

**Comment by thecolinscott** [comment]
Have now discovered that these symptoms were caused by a DNS failure elsewhere on the network.

**Comment by thecolinscott** [comment]
NO ERROR, NO BUG
