### ISSUE TITLE
[Bug]: Cannot login to EUFY account

### ISSUE THREAD

**Issue by hayeskl** [homebridge-eufy-security/plugin#34]
### What happened?

I can no longer long in to my account.  I have tried the latest 1.0.8 version as well as 2.0.0.beta9.   From the status logs it looks like an issue connecting to security-app.eufylife.com

eta.9
[5/18/2022, 6:20:18 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /auth
[5/18/2022, 6:20:18 PM] [Homebridge UI] [homebridge-eufy-security] [2.0.0-beta.9] INFO:  Authentication properties changed, invalidate saved cloud token.
[5/18/2022, 6:20:19 PM] [Homebridge UI] [homebridge-eufy-security] [2.0.0-beta.9] ERROR: Generic Error: RequestError: getaddrinfo ENOTFOUND security-app.eufylife.com
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-eufy-security/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/homebridge/node_modules/homebridge-eufy-security/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  code: 'ENOTFOUND',
  timings: {
    start: 1652912419896,
    socket: 1652912419897,
    lookup: 1652912419922,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1652912419923,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 25,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 27
    }
  }
}

### Device Type

Station (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

**Comment by hayeskl** [comment]
yes

>

**Comment by lenoxys** [comment]
Did you still have the issue ? I've implemented a reset button into advanced settings can you try it ?

**Comment by hayeskl** [comment]
I tried the reset in advance settings and then restarted homebridge.   However, I am still getting the following error when trying to log in with user, password, and United States in the country field.

[5/22/2022, 10:48:33 AM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /auth
[5/22/2022, 10:48:35 AM] [Homebridge UI] [homebridge-eufy-security] [2.0.0-beta.9] ERROR: Generic Error: RequestError: getaddrinfo ENOTFOUND security-app.eufylife.com
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-eufy-security/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/homebridge/node_modules/homebridge-eufy-security/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  code: 'ENOTFOUND',
  timings: {
    start: 1653230915042,
    socket: 1653230915043,
    lookup: 1653230915071,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1653230915072,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 28,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 30
    }
  }
}

**Comment by lenoxys** [comment]
Which country did you use in Eufy App ?

**Comment by hayeskl** [comment]
My Region is United States in the app and two factor authentication is disabled.

**Comment by lenoxys** [comment]
Are you using a guest admin account ?

**Comment by hayeskl** [comment]
No.  I don't have any shared access to my account.

**Comment by hayeskl** [comment]
I was able to reset the DNS server settings on my router and I can now connect.   Thanks for the help
