### ISSUE TITLE
[Bug]: Doorbell camera can't stream video or receive snapshots regardless of settings

### ISSUE THREAD

**Issue by flareman** [homebridge-eufy-security/plugin#372]
### What happened?

I am using the plugin on a homebridge installation running on my Synology DS920+ (DSM 7.2-64570 Update 3, Linux Synology 4.4.302+ #64570). Everything is working normally (motion detection, HomeBase alarm states, other plugins etc.), homebridge is installed via the SynoCommunity repo as instructed by the homebridge wiki, ffmpeg4/5/6 and kernel headers for compiling are also installed as per the same instructions, and the ffmpeg versions installed are 4.1.9, 5.1.3-2 and 6.0-2. For no lack of effort, my Doorbell camera can't stream, nor receive any snapshots. I recently moved my installation to a standalone homebridge installation (prior to that, I was running homebridge in a DietPi VM on the same NAS, with no issues whatsoever; reason for migration was to reduce overhead). Ever since the move, i have this issue. I have tried all steps in the Common Issues and Streaming wiki pages (reducing quality to Low, trying out different presets, restarting the HomeBase, disabling Talkback and Audio, using Cloud Snapshots), as well as reinstalling the plugin after clearing out the entire installation including settings and devices, reinstalling ffmpeg. Still no luck.

I suspect it has something to do with the ffmpeg installation, but I'm at a loss on how to proceed with debugging. Any ideas? Please let me know what else I can try and report back. Thanks in advance 🙏🏻

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
[...]
[8/21/2023, 12:35:33 PM] [EufySecurity-2.2.2] INFO:  You're using guest admin account with this plugin! This is recommanded way!
[8/21/2023, 12:35:33 PM] [EufySecurity-2.2.2] INFO:  Updating accessory: Homebase 2
[8/21/2023, 12:35:33 PM] [Dining Room Camera] current power state: on
[8/21/2023, 12:35:34 PM] [EufySecurity-2.2.2] INFO:  Doorbell Setting up automatic snapshot refresh every 10 minutes. This may decrease battery life dramatically. The refresh process for Doorbell should begin in 1 minutes.
[8/21/2023, 12:35:34 PM] [EufySecurity-2.2.2] INFO:  Doorbell is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[8/21/2023, 12:35:34 PM] [EufySecurity-2.2.2] INFO:  Adding new unbridged accessory: Doorbell
[8/21/2023, 12:35:34 PM] Publishing external accessory (name: Doorbell, publishInfo: {
  username: '6F:24:C5:FF:0A:FD',
  pincode: '***-**-***',
  category: 1,
  port: undefined,
  bind: [ [length]: 0 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'ciao'
}).
[8/21/2023, 12:35:34 PM] Doorbell 12A8 is running on port 38190.
[8/21/2023, 12:35:34 PM] Please add [Doorbell 12A8] manually in Home app. Setup Code: 221-03-331
[8/21/2023, 12:35:34 PM] [EufySecurity-2.2.2] WARN:  Doorbell Couldt not get cloud snapshot: Error: unable to verify the first certificate
[8/21/2023, 12:35:34 PM] [EufySecurity-2.2.2] WARN:  Doorbell snapshot handler is initialized without cloud snapshot. Maybe no snapshot will displayed the first times.
[...]
[8/21/2023, 12:35:40 PM] [EufySecurity-2.2.2] ERROR: Doorbell No snapshot in memory
[Doorbell 12A8] Snapshot request handler provided empty image buffer!
[...]
[8/21/2023, 12:35:48 PM] [homebridge-eufy-security] Error: 
    at Accessory.sendCharacteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2031:14)
    at Timeout._onTimeout (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1732:14)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[...]
[8/21/2023, 12:35:54 PM] [homebridge-eufy-security] This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Doorbell 12A8' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[8/21/2023, 12:35:54 PM] [homebridge-eufy-security] Error: 
    at Accessory.sendCharacteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2031:14)
    at Timeout._onTimeout (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1747:16)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[8/21/2023, 12:35:55 PM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/21/2023, 12:35:55 PM] [EufySecurity-2.2.2] ERROR: Doorbell Unable to start the livestream: no started livestream found
[8/21/2023, 12:35:56 PM] [EufySecurity-2.2.2] ERROR: Doorbell No snapshot in memory
[Doorbell 12A8] Snapshot request handler provided empty image buffer!
[...]
[8/21/2023, 12:36:17 PM] [EufySecurity-2.2.2] INFO:  Looking for old cached accessories that seem to be outdated...
[8/21/2023, 12:36:17 PM] [EufySecurity-2.2.2] INFO:  No outdated cached accessories found.
[...]
[8/21/2023, 12:36:44 PM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/21/2023, 12:36:44 PM] [EufySecurity-2.2.2] WARN:  Doorbell Could not get snapshot from livestream!
[8/21/2023, 12:36:44 PM] [EufySecurity-2.2.2] WARN:  Doorbell No camera source detected.
[...]
```

### config

```shell
[...]
        {
            "platform": "EufySecurity",
            "username": "xxx@xxx.xxx",
            "password": "xxx",
            "country": "GR",
            "deviceName": "",
            "ignoreDevices": [
                "XXX",
                "XXX"
            ],
            "cameras": [
                {
                    "serialNumber": "XXX",
                    "rtsp": false,
                    "enableCamera": true,
                    "videoConfig": {
                        "audio": false,
                        "debug": true,
                        "vcodec": "copy",
                        "useSeparateProcesses": true
                    },
                    "talkback": false,
                    "enableButton": false,
                    "motionButton": false,
                    "unbridge": true,
                    "refreshSnapshotIntervalMinutes": 10,
                    "useCachedLocalLivestream": true
                }
            ],
            "ignoreStations": [],
            "cleanCache": true
}
[...]
```

**Comment by turagit** [comment]
I have the small issue too.

[8/22/2023, 9:42:24 AM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge Ubuntu) is running on port 51933.
[8/22/2023, 9:42:25 AM] [EufySecurity-2.2.2] INFO:  You're using guest admin account with this plugin! This is recommanded way!
[8/22/2023, 9:42:26 AM] [EufySecurity-2.2.2] INFO:  Doorbell is set to balanced snapshot handling.
[8/22/2023, 9:42:26 AM] [EufySecurity-2.2.2] INFO:  Updating accessory: Doorbell
[8/22/2023, 9:42:26 AM] [EufySecurity-2.2.2] WARN:  Doorbell Couldt not get cloud snapshot: Error: connect ECONNREFUSED ::1:443
[8/22/2023, 9:42:26 AM] [EufySecurity-2.2.2] WARN:  Doorbell snapshot handler is initialized without cloud snapshot. Maybe no snapshot will displayed the first times.
[8/22/2023, 9:42:43 AM] [EufySecurity-2.2.2] ERROR: Doorbell No snapshot in memory
[Doorbell] Snapshot request handler provided empty image buffer!
[8/22/2023, 9:42:53 AM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/22/2023, 9:42:53 AM] [EufySecurity-2.2.2] ERROR: Doorbell Unable to start the livestream: no started livestream found
[8/22/2023, 9:43:10 AM] [EufySecurity-2.2.2] INFO:  Looking for old cached accessories that seem to be outdated...
[8/22/2023, 9:43:10 AM] [EufySecurity-2.2.2] INFO:  No outdated cached accessories found.

**Comment by flareman** [comment]
Yes, as stated in the original bug report.

**Comment by flareman** [comment]
Update: after a while, the plugin crashes homebridge with the following:

'''
[...]
[8/23/2023, 9:31:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell Could not get snapshot from livestream!
[8/23/2023, 9:31:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell No camera source detected.
[8/23/2023, 9:41:11 AM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/23/2023, 9:41:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell Could not get snapshot from livestream!
[8/23/2023, 9:41:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell No camera source detected.
[8/23/2023, 9:51:11 AM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/23/2023, 9:51:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell Could not get snapshot from livestream!
[8/23/2023, 9:51:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell No camera source detected.
[8/23/2023, 10:01:11 AM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/23/2023, 10:01:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell Could not get snapshot from livestream!
[8/23/2023, 10:01:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell No camera source detected.
[8/23/2023, 10:11:11 AM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/23/2023, 10:11:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell Could not get snapshot from livestream!
[8/23/2023, 10:11:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell No camera source detected.
[...]
[8/23/2023, 10:21:11 AM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/23/2023, 10:21:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell Could not get snapshot from livestream!
[8/23/2023, 10:21:11 AM] [EufySecurity-2.2.2] WARN:  Doorbell No camera source detected.
[8/23/2023, 10:27:42 AM] [EufySecurity-2.2.2] INFO:  Doorbell ON Event Detected (motion detected): true
(node:22481) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 livestream start listeners added to [LocalLivestreamManager]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[8/23/2023, 10:27:52 AM] [EufySecurity-2.2.2] INFO:  Doorbell ON Event Detected (motion detected): false
[8/23/2023, 10:27:52 AM] [EufySecurity-2.2.2] ERROR: Doorbell Local livestream didn't start in time. Abort livestream request.
[8/23/2023, 10:27:52 AM] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "no started livestream found".
'''

**Comment by lenoxys** [comment]
can you try disabling "Use Local Livestream Caching" ?

**Comment by flareman** [comment]
Just updated to 2.2.5, everything works perfectly with the settings set as before without me needing to change anything. Thanks! 🙏🏻🙏🏻

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
