### ISSUE TITLE
[Bug]: Eufy S120 Solar Wall Cam Support

### ISSUE THREAD

**Issue by cello8619** [homebridge-eufy-security/plugin#392]
### What happened?

I am writing since it seems the new Dufy S120 is not supported, do you have this on your radar for support going forward?  If so is there an ETA?

### Device Type

other (UnSupported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
fySecurity-2.2.6]       DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / Manufacturer': Eufy
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / Model': WALL_LIGHT_CAM_81A0
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / Name': Side Fence Left
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / SerialNumber': T81A0P10233217D8
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / FirmwareRevision': 1.1.6.7
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / HardwareRevision': 1.0.0.0
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:421]        Side Fence Left GET EventSnapshotsActive: 0
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'CameraOperatingMode / EventSnapshotsActive': [object Promise]
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:313]        Side Fence Left GET 'this.platform.Characteristic.HomeKitCameraActive' enabled: undefined
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'CameraOperatingMode / HomeKitCameraActive': false
[09/01/2023 20:28:43]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:313]        Side Fence Left GET 'this.platform.Characteristic.MotionDetected' motionDetected: false
[9/1/2023, 4:28:44 PM] [myQ] myQ API: Discovered device family camera: Garage Camera (serial number: TC-0003-8886721).
[9/1/2023, 4:28:44 PM] [myQ] myQ API: Discovered device family garagedoor: Garage Door [Liftmaster Commercial WiFi Wall Mount Operator] (serial number: CG28634AD80C, gateway: GW12000B1B1A).
[9/1/2023, 4:28:44 PM] [myQ] myQ API: Discovered device family gateway: Garage Door [Chamberlain WiFi GDO DC 1.25 HP] (serial number: GW12000B1B1A).
[9/1/2023, 4:28:44 PM] [myQ] myQ device family 'camera' is not currently supported, ignoring: Garage Camera (serial number: TC-0003-8886721).
[9/1/2023, 4:28:44 PM] [BlueAir] Creating new object: BlueAirDustProtectAccessory
[9/1/2023, 4:28:44 PM] [BlueAir] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    ERROR   [StationAccessory.ts:288]       Side Fence Left handleSecuritySystemCurrentStateGet Wrong return value
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'SecuritySystem / SecuritySystemCurrentState': false
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    ERROR   [StationAccessory.ts:305]       Side Fence Left handleSecuritySystemTargetStateGet Wrong return value
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'SecuritySystem / SecuritySystemTargetState': false
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'Switch / On': false
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:421]        Side Fence Left GET EventSnapshotsActive: 0
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'CameraOperatingMode / EventSnapshotsActive': [object Promise]
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:313]        Side Fence Left GET 'this.platform.Characteristic.HomeKitCameraActive' enabled: undefined
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'CameraOperatingMode / HomeKitCameraActive': false
[09/01/2023 20:28:45]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:313]        Side Fence Left GET 'this.platform.Characteristic.MotionDetected' motionDetected: false
[9/1/2023, 4:28:46 PM] [BlueAir] Removing stale Service: uuid:[0000008A-0000-1000-8000-0026BB765291]
[9/1/2023, 4:28:46 PM] [BlueAir] Removing stale Service: uuid:[00000082-0000-1000-8000-0026BB765291]
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / Manufacturer': Eufy
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / Model': WALL_LIGHT_CAM_81A0
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / SerialNumber': T81A0P10233217D8
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / FirmwareRevision': 1.1.6.7
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [platform.ts:209]       Push Connected!
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / Manufacturer': Eufy
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / Model': WALL_LIGHT_CAM_81A0
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / SerialNumber': T81A0P10233217D8
[09/01/2023 20:28:47]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'AccessoryInformation / FirmwareRevision': 1.1.6.7
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    ERROR   [StationAccessory.ts:288]       Side Fence Left handleSecuritySystemCurrentStateGet Wrong return value
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'SecuritySystem / SecuritySystemCurrentState': false
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    ERROR   [StationAccessory.ts:305]       Side Fence Left handleSecuritySystemTargetStateGet Wrong return value
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'SecuritySystem / SecuritySystemTargetState': false
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'Switch / On': false
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:421]        Side Fence Left GET EventSnapshotsActive: 0
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'CameraOperatingMode / EventSnapshotsActive': [object Promise]
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:313]        Side Fence Left GET 'this.platform.Characteristic.HomeKitCameraActive' enabled: undefined
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'CameraOperatingMode / HomeKitCameraActive': false
[09/01/2023 20:28:50]   [EufySecurity-2.2.6]    DEBUG   [CameraAccessory.ts:313]        Side Fence Left GET 'this.platform.Characteristic.MotionDetected' motionDetected: false
[09/01/2023 20:29:13]   [EufySecurity-2.2.6]    ERROR   [StationAccessory.ts:288]       Side Fence Left handleSecuritySystemCurrentStateGet Wrong return value
[09/01/2023 20:29:13]   [EufySecurity-2.2.6]    DEBUG   [BaseAccessory.ts:125]  Side Fence Left GET 'SecuritySystem / SecuritySystemCurrentState': false
[09/01/2023 20:29:20]   [EufySecurity-2.2.6]    INFO    [platform.ts:413]       Looking for old cached accessories that seem to be outdated...
[09/01/2023 20:29:20]   [EufySecurity-2.2.6]    INFO    [platform.ts:429]       No outdated cached accessories found.
[9/1/2023, 4:29:30 PM] [Homebridge UI] Asset Not Found: homebridge-eufy-security/assets/devices/walllight_s100_large
[9/1/2023, 4:29:30 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[9/1/2023, 4:29:31 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[9/1/2023, 4:29:34 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /downloadLogs
[9/1/2023, 4:29:34 PM] [Homebridge UI] [homebridge-eufy-security] [09/01/2023 20:29:34] [EufySecurity-2.2.6]    INFO    [server.js:267] compressing log files to /var/lib/homebridge/eufysecurity/logs.zip and sending to client.
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [SnapshotManager.ts:282]        Side Fence Left Automatic snapshot refresh triggered.
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [SnapshotManager.ts:320]        Side Fence Left Locked refresh process.
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [SnapshotManager.ts:321]        Side Fence Left Fetching new snapshot from camera.
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [utils.ts:8]    Side Fence Left RTSP rtspStream:false
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [utils.ts:10]   Side Fence Left Looks like not compatible with RTSP
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [LocalLivestreamManager.ts:214] Side Fence Left New instance requests livestream. There were 0 instance(s) using the livestream until now.
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [LocalLivestreamManager.ts:233] Side Fence Left Start new station livestream (P2P Session)...
[9/1/2023, 4:29:40 PM] NotSupportedError: This functionality is not implemented or supported by this device
    at EufySecurity.startStationLivestream (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:834:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/1/2023, 4:29:40 PM] Got SIGTERM, shutting down Homebridge...
[9/1/2023, 4:29:40 PM] [Harmony Hub] INFO - shutdown
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [platform.ts:212]       Push Closed!
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [platform.ts:218]       Closed!
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    INFO    [platform.ts:394]       Finished shutdown!
[09/01/2023 20:29:40]   [EufySecurity-2.2.6]    DEBUG   [LocalLivestreamManager.ts:283] Side Fence Left Stopping station livestream.
[9/1/2023, 4:29:40 PM] NotSupportedError: This functionality is not implemented or supported by this device
    at EufySecurity.stopStationLivestream (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:882:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### config

```shell
{
            "enableDetailedLogging": true,
            "enableCamera": false,
            "CameraMaxLivestreamDuration": 30,
            "pollingIntervalMinutes": 10,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "ignoreStations": [],
            "ignoreDevices": [],
            "country": "US",
            "ffmpegdebug": false,
            "cameras": [
                {
                    "serialNumber": "************",
                    "rtsp": false,
                    "enableCamera": "true",
                    "videoConfig": {
                        "audio": true,
                        "audioSampleRate": 0
                    },
                    "talkback": true,
                    "snapshotHandlingMethod": 3,
                    "refreshSnapshotIntervalMinutes": 10
                }
            ],
            "cleanCache": true,
            "unbridge": true,
            "platform": "EufySecurity",
            "username": "XXXXXXX@XXXX.com",
            "password": "XXXXXX",
            "deviceName": ""
        }
```

**Comment by lenoxys** [comment]
can you send me yours logs ? https://github.com/homebridge-eufy-security/plugin/wiki/Basic-Troubleshooting

**Comment by cello8619** [comment]
Here are my logs:

[configui-server.log](https://github.com/homebridge-eufy-security/plugin/files/12501690/configui-server.log)
[log-lib.log](https://github.com/homebridge-eufy-security/plugin/files/12501691/log-lib.log)
[eufy-log.log](https://github.com/homebridge-eufy-security/plugin/files/12501692/eufy-log.log)

**Comment by lenoxys** [comment]
Ok in fact as per lib description this device is not yet supported : https://bropat.github.io/eufy-security-client/#/supported_devices

You can add your 2 cents here : https://github.com/bropat/eufy-security-client/issues/366

**Comment by athal7** [comment]
The latest release of eufy-security-client added support for this device 
https://github.com/bropat/eufy-security-client/releases/tag/3.0.0

**Comment by athal7** [comment]
Running on the latest hksv release 2.3.11, all of the switches and sensors show up, but not the camera (tried bridged vs unbridged, hksv and regular camera). Error for unbridged with no hksv:
```log
[03/11/2024, 12:06:28]  [EufySecurity]  ERROR   Solar Wall Light Cam while happending Delegate TypeError: Cannot read properties of undefined (reading 'log')
```

**Comment by town3r** [comment]
Currently expected.

No cameras or streaming is working atm.

Current version was to see / get the new devices to show up "correctly".

**Comment by athal7** [comment]
@town3r No cameras or streaming working on the hksv branch? Or on the main branch as well?

**Comment by town3r** [comment]
Only the hksv branch which is the only one w/ the new v3.0 device library.

**Comment by athal7** [comment]
These logs are from a homebridge running the plugin off of that branch

**Comment by lenoxys** [comment]
yeah no streaming on HKSV and the main branch don't support the new device

**Comment by athal7** [comment]
debug/error logs running on v3.0.0:
```
[04/16/2024 11:45:37]   [EufySecurity-3.0.0]    DEBUG   [BaseAccessory.ts:157]  Solar Wall Light Cam GET 'AccessoryInformation / HardwareRevision': 1.0.0.0
[04/16/2024 11:45:37]   [EufySecurity-3.0.0]    ERROR   [StationAccessory.ts:323]     Solar Wall Light Cam handleSecuritySystemCurrentStateGets: Wrong return value
[04/16/2024 11:45:37]   [EufySecurity-3.0.0]    DEBUG   [BaseAccessory.ts:157]  Solar Wall Light Cam GET 'SecuritySystem / SecuritySystemCurrentState': false
[04/16/2024 11:45:37]   [EufySecurity-3.0.0]    ERROR   [StationAccessory.ts:323]     Solar Wall Light Cam handleSecuritySystemTargetStateGet: Wrong return value
```

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
