### ISSUE TITLE
[Bug]: Plugin Causes System Crash/Boot Loop

### ISSUE THREAD

**Issue by MartinJRS** [homebridge-eufy-security/plugin#395]
### What happened?

Hello everyone. Since I updated to 2.2.7 yesterday, it seems that the "Homebridge-eufy-security" plugin is causing a significant issue. Right after the update, it triggers a "boot loop," with Homebridge crashing and restarting immediately, over and over again.

Can anyone else report a similar problem? What can be done?

Thanks a lot.

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[09/02/2023 08:07:55]   [EufySecurity-2.2.6]    INFO    Finished shutdown!
[09/02/2023 08:07:55]   [EufySecurity-2.2.6]    INFO    Finished shutdown!
[02/09/2023, 10:07:55] Error: 
      You're not using guest admin account with this plugin! This is not recommanded way!
      Please look here for more details: https://github.com/homebridge-eufy-security/plugin/wiki/Installation
      T8010P2321123F23 type: 2
      
    at EufySecurityPlatform.stationAdded (/usr/local/lib/node_modules/homebridge-eufy-security/src/plugin/platform.ts:269:13)
    at EufySecurity.emit (node:events:514:28)
    at EufySecurity.emit (node:domain:489:12)
    at EufySecurity.addStation (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:273:18)
    at /usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:499:30
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
[02/09/2023, 10:07:55] Error: 
      You're not using guest admin account with this plugin! This is not recommanded way!
      Please look here for more details: https://github.com/homebridge-eufy-security/plugin/wiki/Installation
      T8410P3122181667 type: 0
      
    at EufySecurityPlatform.stationAdded (/usr/local/lib/node_modules/homebridge-eufy-security/src/plugin/platform.ts:269:13)
    at EufySecurity.emit (node:events:514:28)
    at EufySecurity.emit (node:domain:489:12)
    at EufySecurity.addStation (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:273:18)
    at /usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:499:30
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
[02/09/2023, 10:07:55] Got SIGTERM, shutting down Homebridge...
[09/02/2023 08:07:55]   [EufySecurity-2.2.6]    INFO    Finished shutdown!
[02/09/2023, 10:07:55] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:514:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Katzen-Cam is set to generate new snapshots on events every time. This might reduce homebridge performance and increase power consumption.
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Wohnzimmer Kamera is set to generate new snapshots on events every time. This might reduce homebridge performance and increase power consumption.
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Flur Kamera is set to generate new snapshots on events every time. This might reduce homebridge performance and increase power consumption.
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Updating existing accessory: Bewegungssensor Flur
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Updating existing accessory: Sensor Wohnzimmer rechts
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Sensor Wohnzimmer rechts ON 'ContactSensor / ContactSensorState / open': false
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Updating existing accessory: Sensor Wohnzimmer links
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Sensor Wohnzimmer links ON 'ContactSensor / ContactSensorState / open': false
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Updating existing accessory: Sensor Haustür
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Sensor Haustür ON 'ContactSensor / ContactSensorState / open': false
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Updating existing accessory: Sensor Gäste WC
[09/02/2023 08:07:56]   [EufySecurity-2.2.6]    INFO    Sensor Gäste WC ON 'ContactSensor / ContactSensorState / open': false
[09/02/2023 08:07:57]   [EufySecurity-2.2.6]    INFO    Updating existing accessory: Sensor Wohnzimmer seitlich
[09/02/2023 08:07:57]   [EufySecurity-2.2.6]    INFO    Sensor Wohnzimmer seitlich ON 'ContactSensor / ContactSensorState / open': false
[09/02/2023 08:07:57]   [EufySecurity-2.2.6]    INFO    Updating existing accessory: Sensor Küche
[09/02/2023 08:07:57]   [EufySecurity-2.2.6]    INFO    Sensor Küche ON 'ContactSensor / ContactSensorState / open': false
```

### config

```shell
{
            "platform": "EufySecurity",
            "username": "******.******@******",
            "password": "******-******-******",
            "country": "DE",
            "ignoreStations": [],
            "ignoreDevices": [
                "T811....",
                "T811....",
                "T811....",
                "T896....",
                "T811...."
            ],
            "pollingIntervalMinutes": 1,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": false,
            "CameraMaxLivestreamDuration": 30,
            "cleanCache": true,
            "cameras": [
                {
                    "serialNumber": "T811....",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": false,
                    "forcerefreshsnap": false,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "T811....",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": false,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    }
                },
                {
                    "serialNumber": "T811....",
                    "enableCamera": true,
                    "enableButton": true,
                    "motionButton": true,
                    "rtsp": true,
                    "unbridge": false,
                    "forcerefreshsnap": true,
                    "useCachedLocalLivestream": true,
                    "videoConfig": {
                        "audio": true
                    }
                }
            ],
            "preferLocalConnection": true
        },
```

**Comment by MartinJRS** [comment]
Yes, I did.

**Comment by lenoxys** [comment]
as per log your using the super account admin instead of guest one

I have enforced the usage of guest admin to unsure we not lock the super one 

https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin

**Comment by MartinJRS** [comment]
Okay, I have switched it ... never caused issues before. Thanks you very much.

Now, there is a new issue ... now, on the Eufy Base I can only choose between "Home", "Absent" and "Off". Until these issues, I was able to also choose "Night Mode", but that's gone now. Any Idea what happened? Did Eufy change such things?

**Comment by lenoxys** [comment]
It will be fixed on the next version.

**Comment by MartinJRS** [comment]
Ah, okay. Thanks a lot.

**Comment by lenoxys** [comment]
#398

**Comment by MartinJRS** [comment]
Wow, you have fixed it. Wonderful, thanks for helping that quickly.
