### ISSUE TITLE
[Bug]: 2.0.0 Issue with plugin crashing after install

### ISSUE THREAD

**Issue by pogglywoggly** [homebridge-eufy-security/plugin#41]
### What happened?

When installing the latest 2.0.0 release plugin crashes on me and cannot get into settings to program the plugin.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[5/27/2022, 9:52:57 AM] [Homebridge UI] Running Command: npm install -g homebridge-eufy-security@latest
[5/27/2022, 9:53:16 AM] [Homebridge UI] [homebridge-eufy-security] /usr/local/lib/node_modules/homebridge-eufy-security/homebridge-ui/server.js:107
      this.config['country'] = body.country ??= 'US';
                                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
[5/27/2022, 9:53:16 AM] [Homebridge UI] [homebridge-eufy-security] Child process ended
[5/27/2022, 9:53:22 AM] [Homebridge UI] Changes to config.json saved.
[5/27/2022, 9:53:22 AM] [Homebridge UI] [homebridge-eufy-security] Terminating child process...
```

**Comment by pogglywoggly** [comment]
yep 

> Did you check this [Common Issues](https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues) pages ?

**Comment by pogglywoggly** [comment]
That did the trick. Thank you!

**Comment by lenoxys** [comment]
hello this has been fixed on latest beta version.
