### ISSUE TITLE
[Bug]: Eufy Door Lock state not reported properly when unlocked

### ISSUE THREAD

**Issue by zthun** [homebridge-eufy-security/plugin#411]
### What happened?

It looks like 2.2.14 fixes the missing Eufy lock and I can toggle the locked and unlocked state, but I'm seeing issues with the reporting of the lock state. 

Logs report a wrong value of 3 where the maximum value is 1.

### Device Type

other (UnSupported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
[09/09/2023 04:54:56]   [EufySecurity-2.2.14]   WARN    [LockAccessory.ts:110]  Front Door Something wrong on the lockstatus feedback
[9/8/2023, 11:54:56 PM] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Lock Target State': characteristic was supplied illegal value: number 3 exceeded maximum of 1. See https://homebridge.io/w/JtMGR for more info.
[9/8/2023, 11:54:56 PM] [homebridge-eufy-security] Error: 
    at LockTargetState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at LockTargetState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2927:14)
    at LockTargetState.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at Lock.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/src/plugin/accessories/LockAccessory.ts:54:28)
    at Lock.emit (node:events:525:35)
    at Lock.emit (node:domain:489:12)
    at Lock.handlePropertyChange (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:2703:18)
    at Lock.updateProperty (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:79:22)
    at Lock.handlePropertyChange (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:2707:18)
    at Lock.updateProperty (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:79:22)
[9/8/2023, 11:55:01 PM] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes/160062726685392462
[9/8/2023, 11:55:01 PM] [LGThinQ] [Dishwasher] Received snapshot:  {"dishwasher":{"door":"CLOSE","courseType":"COURSE","initialTimeMinute":34,"mcReminder":"OFF","preSteam":"OFF","saltRefill":"NOT_SET","energySaver":"OFF","error":"ERROR_NO","nightDry":"ON","extraDry":"OFF","remainTimeHour":0,"course":"HEAVY/INTENSIVE","dualZone":"OFF","highTemp":"OFF","state":"RUNNING","process":"NIGHTDRY","reserveTimeMinute":0,"currentDownloadCourse":"POTS_PANS","cleanLReminder":"ON","rinseLevel":"LEVEL_2","signalLevel":"LEVEL_ON","remainTimeMinute":1,"reserveTimeHour":0,"delayStart":"OFF","softeningLevel":"LEVEL_0","tclCount":54,"smartCourse":"NONE","childLock":"OFF","rinseRefill":"NOT_SET","halfLoad":"OFF","initialTimeHour":3},"mid":12623912,"online":true,"static":{"deviceType":"204","countryCode":"US"},"meta":{"allDeviceInfoUpdate":false,"messageId":"7_alvYAjR4CNjn06asxXgA"},"timestamp":1694229857486}
```

### config

```shell
{
    "username": "<Redacted>",
    "password": "<Redacted>",
    "country": "US",
    "deviceName": "",
    "platform": "EufySecurity",
    "ignoreStations": [
        "T8410P3121365E64",
        "T8410P4122322C95"
    ],
    "ignoreDevices": [
        "T8410P3121365E64",
        "T8410P4122322C95"
    ],
    "cleanCache": true,
    "cameras": [
        {
            "serialNumber": "T8422T10212800E8",
            "rtsp": false,
            "enableCamera": "true",
            "videoConfig": {
                "vcodec": "copy",
                "useSeparateProcesses": true
            }
        },
        {
            "serialNumber": "T8210P002041022D",
            "rtsp": false,
            "enableCamera": true,
            "videoConfig": {
                "vcodec": "copy",
                "useSeparateProcesses": true
            }
        },
        {
            "serialNumber": "T8142T4322421054",
            "enableCamera": "true",
            "videoConfig": {
                "vcodec": "copy",
                "useSeparateProcesses": true
            }
        },
        {
            "serialNumber": "T8142N432243119D",
            "videoConfig": {
                "vcodec": "copy",
                "useSeparateProcesses": true
            },
            "enableCamera": "true"
        },
        {
            "serialNumber": "T8142N4322431505",
            "enableCamera": "true",
            "videoConfig": {
                "vcodec": "copy",
                "useSeparateProcesses": true
            }
        },
        {
            "serialNumber": "T8422T102320011B",
            "rtsp": false,
            "enableCamera": "true",
            "videoConfig": {
                "audio": true,
                "vcodec": "copy",
                "useSeparateProcesses": true
            },
            "talkback": false,
            "refreshSnapshotIntervalMinutes": 0
        }
    ],
    "enableDetailedLogging": true
}
```

**Comment by lenoxys** [comment]
This is a duplicate of #407
