### ISSUE TITLE
[Bug]: Plugin crashes homebridge instance when changing station guard mode to disarmed

### ISSUE THREAD

**Issue by flareman** [homebridge-eufy-security/plugin#446]
### What happened?

When attempting to change the arming status of my Homebase 2 to disarmed, the plugin crashes, carrying the entire homebridge instance along with it. Attempting to arm as any of the other modes does work, but error messages appear in the log. I'm running on a Synology DS920+ on DSM7. I haven't had any issues until a few plugin versions back (can't say for sure when this behavior started), and I noticed only incidentally, because the crashing of the HB instance was resetting some of my dummy switches from another plugin, so I checked the logs and found out about this.

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
Homebridge initial startup; Homebase is armed as Home:

[10/6/2023, 11:40:32 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /volume1/homebridge/node_modules --strict-plugin-resolution
[...]
[10/6/2023, 11:40:34 AM] Loaded plugin: homebridge-eufy-security@2.2.21
[10/6/2023, 11:40:34 AM] Registering platform 'homebridge-eufy-security.EufySecurity'
[...]
[10/06/2023, 11:40:35]  [EufySecurity]  WARN    warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[10/06/2023, 11:40:36]  [EufySecurity]  INFO    Country set: GR
[10/06/2023, 11:40:36]  [EufySecurity]  INFO    Finished initializing!
[...]
[10/06/2023, 11:40:47]  [EufySecurity]  INFO    Updating existing accessory: Homebase 2
[10/6/2023, 11:40:51 AM] [yeelight] All known devices found. Stopping proactive search.
[10/06/2023, 11:40:54]  [EufySecurity]  INFO    Doorbell Setting up automatic snapshot refresh every 10 minutes. This may decrease battery life dramatically. The refresh process for Doorbell should begin in 1 minutes.
[10/06/2023, 11:40:54]  [EufySecurity]  INFO    Doorbell is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[10/06/2023, 11:41:23]  [EufySecurity]  INFO    Looking for old cached accessories that seem to be outdated...
[10/06/2023, 11:41:23]  [EufySecurity]  INFO    No outdated cached accessories found.
[...]
[10/06/2023, 11:43:17]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemCurrentStateGets: Wrong return value
[10/06/2023, 11:43:17]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemTargetStateGet: Wrong return value

Attempting to arm for Night arms as Home and the log reports:

[10/06/2023, 11:46:12]  [EufySecurity]  INFO    Homebase 2 Request to change station guard mode to: NIGHT_ARM(2)
[10/06/2023, 11:46:13]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemCurrentStateGets: Wrong return value
[10/06/2023, 11:46:13]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemTargetStateGet: Wrong return value
[10/06/2023, 11:46:18]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemCurrentStateGets: Wrong return value
[10/06/2023, 11:46:38]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemCurrentStateGets: Wrong return value
[10/06/2023, 11:46:38]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemTargetStateGet: Wrong return value
[10/06/2023, 11:46:39]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemCurrentStateGets: Wrong return value
[10/06/2023, 11:46:39]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemTargetStateGet: Wrong return value

Attempting to arm for away works but the log reports:
[10/06/2023, 11:45:26]  [EufySecurity]  INFO    Homebase 2 Request to change station guard mode to: AWAY_ARM(1)
[10/06/2023, 11:45:26]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemTargetStateGet: Wrong return value
[10/06/2023, 11:45:26]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemCurrentStateGets: Wrong return value
[10/06/2023, 11:45:26]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemTargetStateGet: Wrong return value
[10/06/2023, 11:45:27]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemCurrentStateGets: Wrong return value
[10/06/2023, 11:45:27]  [EufySecurity]  ERROR   Homebase 2 handleSecuritySystemTargetStateGet: Wrong return value

Attempting to disarm crashes the instance:

[10/06/2023, 11:47:48]  [EufySecurity]  INFO    Homebase 2 Request to change station guard mode to: DISARM(3)
[10/6/2023, 11:47:48 AM] InvalidPropertyValueError: Invalid value for this property according to metadata
    at validValue (/volume1/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/utils.ts:137:19)
    at Station.setGuardMode (/volume1/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:692:19)
    at StationAccessory.handleSecuritySystemTargetStateSet (/volume1/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:350:19)
    at setValue (/volume1/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:99:33)
    at SecuritySystemTargetState.setHandler (/volume1/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/BaseAccessory.ts:161:25)
    at SecuritySystemTargetState.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
[10/6/2023, 11:47:48 AM] Got SIGTERM, shutting down Homebridge...
[10/6/2023, 11:47:48 AM] [Homebridge UI] Failed to get characteristics for Homebase 2 with iid 10: connect ECONNREFUSED 127.0.0.1:51192
[10/06/2023, 11:47:48]  [EufySecurity]  INFO    Finished shutdown!
[10/06/2023, 11:47:53]  [EufySecurity]  WARN    Homebase 2 Changing guard mode to DISARM(3) did not complete. Retry...'
[10/6/2023, 11:47:53 AM] InvalidPropertyValueError: Invalid value for this property according to metadata
    at validValue (/volume1/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/utils.ts:137:19)
    at Station.setGuardMode (/volume1/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:692:19)
    at Timeout._onTimeout (/volume1/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:359:21)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[10/6/2023, 11:47:53 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

### config

```shell
"platform": "EufySecurity",
            "username": "xxx.xxx@xxx.com",
            "password": "xxx",
            "country": "GR",
            "deviceName": "",
            "ignoreDevices": [
                "XXX",
                "XXX"
            ],
            "cameras": [
                {
                    "serialNumber": "XXX",
                    "rtsp": false,
                    "enableCamera": true,
                    "videoConfig": {
                        "audio": true,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "useSeparateProcesses": true
                    },
                    "talkback": true,
                    "enableButton": false,
                    "motionButton": false,
                    "unbridge": true,
                    "refreshSnapshotIntervalMinutes": 10,
                    "useCachedLocalLivestream": true
                }
            ],
            "ignoreStations": [],
            "cleanCache": true
```

**Comment by flareman** [comment]
Yes I have; nothing there about arming changes and crashes.

**Comment by HenryGelderbloem** [comment]
I have the same issue on a new install. Exact same issue and the same logs.

`{
    "username": "",
    "password": "",
    "country": "GB",
    "deviceName": "Homebridge",
    "platform": "EufySecurity",
    "ignoreStations": [
        "T8400P3223352C2A"
    ],
    "ignoreDevices": [
        "T8113N1320434686",
        "T8113N1320434FDE",
        "T8113N13204354E4",
        "T8113N13204351AC",
        "T8400P3223352C2A"
    ],
    "cleanCache": true,
    "_bridge": {
        "username": "0E:C7:82:C5:3D:1A",
        "port": 47141
    },
    "cameras": [
        {
            "serialNumber": "T8210P0020443DA7",
            "rtsp": false,
            "enableCamera": true,
            "videoConfig": {
                "audio": true,
                "vcodec": "copy",
                "useSeparateProcesses": true
            },
            "talkback": true,
            "snapshotHandlingMethod": 3,
            "immediateRingNotificationWithoutSnapshot": false,
            "delayCameraSnapshot": false,
            "refreshSnapshotIntervalMinutes": 5,
            "useCachedLocalLivestream": false,
            "enableButton": false,
            "motionButton": false,
            "indoorChimeButton": false
        }
    ]
}`

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
