### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Hagalurt** [homebridge-eufy-security/plugin#449]
### What happened?

A crash happened when I attempted to change the states (like changing "At home" to "Night") 

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[10/08/2023, 16:29:04]  [EufySecurity]  INFO    Eufy Homebase Request to change station guard mode to: DISARM(3)
InvalidPropertyValueError: Invalid value for this property according to metadata
    at validValue (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/utils.ts:137:19)
    at Station.setGuardMode (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:692:19)
    at StationAccessory.handleSecuritySystemTargetStateSet (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:350:19)
    at setValue (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:99:33)
    at SecuritySystemTargetState.setHandler (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/BaseAccessory.ts:161:25)
    at SecuritySystemTargetState.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
```

### config

```shell
{
    "username": "XXXXXXX@xxxxx.xxx",
    "password": "xxxxxxxx",
    "country": "FR",
    "deviceName": "",
    "platform": "EufySecurity",
    "ignoreStations": [],
    "ignoreDevices": [],
    "cleanCache": true,
    "_bridge": {
        "username": "xxxxx:91:9A:E1:2C",
        "port": 45571
    }
}
```

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
