### ISSUE TITLE
[Bug]: Red and Green Child bridge Look

### ISSUE THREAD

**Issue by FTSCOOP** [homebridge-eufy-security/plugin#476]
### What happened?

A bug happened!

### Device Type

Indoor Camera (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Error: listen EADDRINUSE: address already in use :::55797
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at EventedHTTPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5
```

### config

```shell
"enableDetailedLogging": false,
    "CameraMaxLivestreamDuration": 30,
    "pollingIntervalMinutes": 1,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "ignoreStations": [],
    "ignoreDevices": [],
    "country": "US",
    "cameras": [
        {
            "serialNumber": "T84A1P102249005D",
            "rtsp": false,
            "enableCamera": true,
            "videoConfig": {
                "audio": true,
                "vcodec": "copy",
                "useSeparateProcesses": true
            },
            "snapshotHandlingMethod": 2
        },
        {
            "serialNumber": "T84A1P10225109C7",
            "rtsp": false,
            "enableCamera": true,
            "videoConfig": {
                "vcodec": "copy",
                "useSeparateProcesses": true,
                "audio": true,
                "audioSampleRate": 0
            },
            "snapshotHandlingMethod": 2
        },
        {
            "serialNumber": "T84A1P102251102D",
            "rtsp": false,
            "enableCamera": true,
            "videoConfig": {
                "audio": true,
                "vcodec": "copy",
                "useSeparateProcesses": true
            },
            "snapshotHandlingMethod": 2
        }
    ],
    "cleanCache": true,
    "unbridge": true,
    "username": "fullltimescoop@gmail.com",
    "password": "THEGREATone#9",
    "deviceName": "newone",
    "platform": "EufySecurity",
    "_bridge": {
        "username": "0E:B2:4C:A1:72:B7",
        "port": 55797
    }
}
```

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
