### ISSUE TITLE
[Bug]: SoloCam S220: Changing alarm mode kills homebridge

### ISSUE THREAD

**Issue by sfriesdorf** [homebridge-eufy-security/plugin#489]
**Setup:**
Running Homebridge on Docker on Raspi 4B
- Homebridge 1.7.0
- Node.js v18.18.2
- homebridge-eufy-security v2.2.21

I had running homebridge with eufy security plugin quite smoothly with a Homebase 2 and two EufyCam 2C Pro (only used as motion sensors) added. Everything worked fine, including alarm mode switching for homebase.

Now I added two new Eufy Solocam S220 ("Haustür" and "Terrasse") to my account/guest account and added them to the eufy homebridge plugin.
First of all - the cameras are not recognized as cameras in the config UI:
<img width="595" alt="image" src="https://github.com/homebridge-eufy-security/plugin/assets/94489365/a9a7f9d6-1449-4629-a6cf-a94480ec2209">

However, the station is displayed as alarm system in my iOS Home app, so homekit integration seems to work for alarm station. But: After switching the alarm mode for one of the Solocams, homebridge encounters an error and restarts, see error message below.
This is strange since the S220 is listed under supported devices: https://bropat.github.io/eufy-security-client/#/supported_devices

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[12/20/2023, 10:52:00]	[EufySecurity]	ERROR	Haustür handleSecuritySystemCurrentStateGets: Wrong return value
[12/20/2023, 10:52:00]	[EufySecurity]	ERROR	Haustür handleSecuritySystemTargetStateGet: Wrong return value
[12/20/2023, 10:52:00]	[EufySecurity]	ERROR	Terrasse handleSecuritySystemTargetStateGet: Wrong return value
[12/20/2023, 10:52:00]	[EufySecurity]	ERROR	Terrasse handleSecuritySystemCurrentStateGets: Wrong return value
[12/20/2023, 10:52:09]	[EufySecurity]	ERROR	Haustür handleSecuritySystemTargetStateGet: true
[12/20/2023, 10:52:10 AM] [deCONZ] Smart plug 1 Consumption: Total Consumption: set to 0.35 kWh (from 0 kWh)
[12/20/2023, 10:52:10 AM] [deCONZ] Smart plug 1 Consumption: Total Consumption: set to 0 kWh (from 0.35 kWh)
[12/20/2023, 10:52:14]	[EufySecurity]	ERROR	Haustür alarm could not be reset: NotSupportedError: This functionality is not implemented or supported
[12/20/2023, 10:52:18]	[EufySecurity]	ERROR	Haustür handleSecuritySystemTargetStateGet: true
[12/20/2023, 10:52:20]	[EufySecurity]	ERROR	Haustür alarm could not be reset: NotSupportedError: This functionality is not implemented or supported
[12/20/2023, 10:52:22]	[EufySecurity]	INFO	Haustür Request to change station guard mode to: AWAY_ARM(1)
[12/20/2023, 10:52:22 AM] NotSupportedError: This functionality is not implemented or supported
    at Station.setGuardMode (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:689:19)
    at StationAccessory.handleSecuritySystemTargetStateSet (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:350:19)
    at setValue (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:99:33)
    at SecuritySystemTargetState.setHandler (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/BaseAccessory.ts:161:25)
    at SecuritySystemTargetState.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:165:16)
[12/20/2023, 10:52:22 AM] Got SIGTERM, shutting down Homebridge...
[12/20/2023, 10:52:22]	[EufySecurity]	INFO	Finished shutdown!
[12/20/2023, 10:52:24 AM] [deCONZ] Phoscon-GW: websocket connection to ws://192.168.0.108:443 closed
[12/20/2023, 10:52:27]	[EufySecurity]	WARN	Haustür Changing guard mode to AWAY_ARM(1) did not complete. Retry...'
[12/20/2023, 10:52:27 AM] NotSupportedError: This functionality is not implemented or supported
    at Station.setGuardMode (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:689:19)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:359:21)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[12/20/2023, 10:52:27 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/20/2023, 10:52:32 AM] [HB Supervisor] Restarting Homebridge...
```

### config

```shell
{
            "platform": "EufySecurity",
            "ignoreStations": [],
            "ignoreDevices": [],
            "cleanCache": true,
            "username": "xxx",
            "password": "xxx",
            "country": "DE",
            "deviceName": "",
            "cameras": [
                {
                    "serialNumber": "T8142T7xxx26",
                    "enableCamera": false,
                    "enableButton": false,
                    "motionButton": false,
                    "talkback": false,
                    "videoConfig": {
                        "audio": false,
                        "audioSampleRate": 0
                    }
                },
                {
                    "serialNumber": "T8142T7xxx68",
                    "videoConfig": {
                        "audio": false,
                        "audioSampleRate": 0
                    },
                    "talkback": false,
                    "enableButton": false,
                    "motionButton": false,
                    "enableCamera": false
                },
                {
                    "serialNumber": "T8134P2xxx1E",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8134P2xxx15",
                    "rtsp": false,
                    "talkback": false
                }
            ],
            "stations": [
                {
                    "hkHome": 1,
                    "hkAway": 0,
                    "serialNumber": "T8134P2xxx1E",
                    "hkNight": 3,
                    "hkOff": 63
                },
                {
                    "hkHome": 1,
                    "hkAway": 0,
                    "serialNumber": "T8134Pxxx15",
                    "hkNight": 3,
                    "hkOff": 63
                }
            ]
        }
```

**Comment by sfriesdorf** [comment]
Anyone an idea? Problem still exists.

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
