### ISSUE TITLE
s220 camera child bridge reboot every time stop streaming or recording.

### ISSUE THREAD

**Issue by toshibochan** [homebridge-eufy-security/plugin#493]
### What happened?

s220 camera child bridge reboot every time stop streaming or recording.

[28/12/2023, 19:50:31] [homebridge-eufy-security] Error: 
    at Accessory.sendCharacteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2031:14)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1732:14)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[swscaler @ 0x7fa6a1d030] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa6a1d030] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa6a1d020] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa6a1d020] [warning] deprecated pixel format used, make sure you did set range correctly
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 192.168.1.86
t=0 0
a=tool:libavformat 60.3.100
m=video 63050 RTP/AVP 99
b=AS:299
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:fuEfXsjZKAWJjMPZCfcxO/xCDfBbgBWFTAhzCA+O

[swscaler @ 0x7fa8d62010] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8d62020] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8d62060] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8d62060] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8020] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8040] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8060] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8020] [warning] deprecated pixel format used, make sure you did set range correctly
[12/28/2023, 19:50:58]  [EufySecurity]  INFO    Backyard Stopped video stream.
Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:217:20)
[28/12/2023, 19:51:00] [homebridge-eufy-security] Child bridge process ended
[28/12/2023, 19:51:00] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
[28/12/2023, 19:51:07] [homebridge-eufy-security] Restarting Process...
[28/12/2023, 19:51:09] [homebridge-eufy-security] Launched child bridge with PID 11113
[28/12/2023, 19:51:11] Registering platform 'homebridge-eufy-security.EufySecurity'
[28/12/2023, 19:51:11] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.3.9 child bridge successfully
[28/12/2023, 19:51:12] Loaded 1 cached accessories from cachedAccessories.0E849722A09A.
[12/28/2023, 19:51:12]  [EufySecurity]  WARN    warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[12/28/2023, 19:51:12]  [EufySecurity]  INFO    ffmpegPath set: /var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/ffmpeg-for-homebridge/ffmpeg
[12/28/2023, 19:51:12]  [EufySecurity]  INFO    Country set: US
[12/28/2023, 19:51:12]  [EufySecurity]  INFO    Finished initializing!
[28/12/2023, 19:51:12] Publishing bridge accessory (name: homebridge-eufy-security, publishInfo: {
  username: 'xx:xx:xxxx:xx:xx',
  port: 42769,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
[28/12/2023, 19:51:12] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-eufy-security) is running on port 42769.
[12/28/2023, 19:51:21]  [EufySecurity]  INFO    Updating existing accessory: Backyard
[12/28/2023, 19:51:23]  [EufySecurity]  INFO    Backyard is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[12/28/2023, 19:51:23]  [EufySecurity]  WARN    Backyard Couldt not get cloud snapshot: TypeError: Cannot read properties of null (reading 'data')
[12/28/2023, 19:51:23]  [EufySecurity]  INFO    WARNING: Motion detection and HomeKit Secure Video provide overlapping functionality. Only HomeKit Secure Video, when event recording is enabled in the Home app, will be used to trigger motion event notifications for this camera.
[12/28/2023, 19:51:24]  [EufySecurity]  INFO    Publishing unbridged accessory externally: Backyard
[12/28/2023, 19:51:24]  [EufySecurity]  WARN    Backyard snapshot handler is initialized without cloud snapshot. Maybe no snapshot will displayed the first times.
[28/12/2023, 19:51:24] Publishing external accessory (name: Backyard, publishInfo: {
  username: 'xx:xx:xx:xx:xx:xx',
  pincode: '***-**-***',
  category: 1,
  port: undefined,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
[28/12/2023, 19:51:24] Backyard 7318 is running on port 42449.
[28/12/2023, 19:51:24] Please add [Backyard 7318] manually in Home app. Setup Code: XXX-XX-XXX

### Device Type

Indoor Camera (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[28/12/2023, 19:50:31] [homebridge-eufy-security] Error: 
    at Accessory.sendCharacteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2031:14)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1732:14)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[swscaler @ 0x7fa6a1d030] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa6a1d030] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa6a1d020] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa6a1d020] [warning] deprecated pixel format used, make sure you did set range correctly
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 192.168.1.86
t=0 0
a=tool:libavformat 60.3.100
m=video 63050 RTP/AVP 99
b=AS:299
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:fuEfXsjZKAWJjMPZCfcxO/xCDfBbgBWFTAhzCA+O

[swscaler @ 0x7fa8d62010] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8d62020] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8d62060] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8d62060] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8020] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8040] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8060] [warning] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fa8fe8020] [warning] deprecated pixel format used, make sure you did set range correctly
[12/28/2023, 19:50:58]  [EufySecurity]  INFO    Backyard Stopped video stream.
Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:217:20)
[28/12/2023, 19:51:00] [homebridge-eufy-security] Child bridge process ended
[28/12/2023, 19:51:00] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
[28/12/2023, 19:51:07] [homebridge-eufy-security] Restarting Process...
[28/12/2023, 19:51:09] [homebridge-eufy-security] Launched child bridge with PID 11113
[28/12/2023, 19:51:11] Registering platform 'homebridge-eufy-security.EufySecurity'
[28/12/2023, 19:51:11] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.3.9 child bridge successfully
[28/12/2023, 19:51:12] Loaded 1 cached accessories from cachedAccessories.0E849722A09A.
[12/28/2023, 19:51:12]  [EufySecurity]  WARN    warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[12/28/2023, 19:51:12]  [EufySecurity]  INFO    ffmpegPath set: /var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/ffmpeg-for-homebridge/ffmpeg
[12/28/2023, 19:51:12]  [EufySecurity]  INFO    Country set: US
[12/28/2023, 19:51:12]  [EufySecurity]  INFO    Finished initializing!
[28/12/2023, 19:51:12] Publishing bridge accessory (name: homebridge-eufy-security, publishInfo: {
  username: 'xx:xx:xx:xx:xx:xx',
  port: 42769,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
[28/12/2023, 19:51:12] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-eufy-security) is running on port 42769.
[12/28/2023, 19:51:21]  [EufySecurity]  INFO    Updating existing accessory: Backyard
[12/28/2023, 19:51:23]  [EufySecurity]  INFO    Backyard is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[12/28/2023, 19:51:23]  [EufySecurity]  WARN    Backyard Couldt not get cloud snapshot: TypeError: Cannot read properties of null (reading 'data')
[12/28/2023, 19:51:23]  [EufySecurity]  INFO    WARNING: Motion detection and HomeKit Secure Video provide overlapping functionality. Only HomeKit Secure Video, when event recording is enabled in the Home app, will be used to trigger motion event notifications for this camera.
[12/28/2023, 19:51:24]  [EufySecurity]  INFO    Publishing unbridged accessory externally: Backyard
[12/28/2023, 19:51:24]  [EufySecurity]  WARN    Backyard snapshot handler is initialized without cloud snapshot. Maybe no snapshot will displayed the first times.
[28/12/2023, 19:51:24] Publishing external accessory (name: Backyard, publishInfo: {
  username: 'xx:xx:xx:xx:xx:xx',
  pincode: '***-**-***',
  category: 1,
  port: undefined,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
[28/12/2023, 19:51:24] Backyard 7318 is running on port 42449.
[28/12/2023, 19:51:24] Please add [Backyard 7318] manually in Home app. Setup Code: XXX-XX-XXX
```

### config

```shell
{
    "bridge": {
        "name": "Homebridge AE47",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51233,
        "pin": "xxx-xx-xxx",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "enableDetailedLogging": false,
            "CameraMaxLivestreamDuration": 30,
            "pollingIntervalMinutes": 10,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "ignoreStations": [],
            "ignoreDevices": [],
            "country": "US",
            "cameras": [
                {
                    "serialNumber": "T8134Pxxxxxxxxxxx",
                    "rtsp": true,
                    "enable": true,
                    "motion": true,
                    "hsv": true,
                    "hsvRecordingDuration": 90,
                    "hsvConfig": {}
                }
            ],
            "cleanCache": true,
            "unbridge": true,
            "ignoreMultipleDevicesWarning": false,
            "syncStationModes": false,
            "username": "XXXXXXXXX",
            "password": "XXXXXXX",
            "deviceName": "XXXXXXX",
            "platform": "EufySecurity",
            "_bridge": {
                "username": "xx:xx:xx:xx:xx:xx",
                "port": 42769
            }
        }
    ]
}
```

**Comment by toshibochan** [comment]
Another problem I having is:
After I pair the camera I can only stream couple times. And after that i can’t anymore. It say no respond.

**Comment by emrenoyan78** [comment]
same issue for me

**Comment by GitlabTonyB** [comment]
When will the plug in work for the eufy SoloCam S340?

**Comment by toshibochan** [comment]
@emrenoyan78  what device you using for the server? I’m using raspberry pi 3 plus.

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
