### ISSUE TITLE
[Bug]: MacOS - When homebridge restarts, eufy-security is reset and removed from automations/rooms

### ISSUE THREAD

**Issue by jackattacck** [homebridge-eufy-security/plugin#50]
### What happened?

When homebridge restarts (after power failure, homebridge-config-ui-x updates, etc), eufy-security seems to be reset and all accessories are removed from rooms and automations and re-added to the default room, leaving me to have to add them again to automations. 

Edit: Just to clarify, the entire plugin is not reset (I do not have to setup again), just the accessories. 

It seems this is a persistence issue, however, I'm not sure how to fix that, since it seems the eufysecurity directory lives outside the persist directory. 

homebridge is running on MacOS 10.15.7

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65456,"level":50,"msg":"Error while shutdown :  TypeError: Cannot read properties of undefined (reading 'close')\n    at EufySecurityPlatform.pluginShutdown (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:173:23)\n    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:149:18)\n    at HomebridgeAPI.emit (node:events:526:28)\n    at HomebridgeAPI.signalShutdown (/usr/local/lib/node_modules/homebridge/src/api.ts:279:10)\n    at BridgeService.teardown (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:571:14)\n    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:183:24)\n    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)\n    at process.emit (node:events:526:28)\n    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)","time":"2022-05-29T13:49:15.529Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65456,"level":30,"msg":"You're using guest admin account with this plugin! This is recommanded way!","time":"2022-05-29T13:49:18.180Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65456,"level":30,"msg":"You're using guest admin account with this plugin! This is recommanded way!","time":"2022-05-29T13:49:18.181Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65456,"level":30,"msg":"You're using guest admin account with this plugin! This is recommanded way!","time":"2022-05-29T13:49:18.181Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65456,"level":30,"msg":"Updating accessory: Homebase 2","time":"2022-05-29T13:49:18.183Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65476,"level":40,"msg":"warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1","time":"2022-05-29T13:49:25.860Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65476,"level":30,"msg":"Country set: US","time":"2022-05-29T13:49:25.863Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65476,"level":30,"msg":"Finished initializing!","time":"2022-05-29T13:49:25.863Z","v":0}
{"name":"[EufySecurity-2.0.0]","hostname":"Mac-mini.local","pid":65476,"level":50,"msg":"Error while shutdown :  TypeError: Cannot read properties of undefined (reading 'close')\n    at EufySecurityPlatform.pluginShutdown (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:173:23)\n    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:149:18)\n    at HomebridgeAPI.emit (node:events:526:28)\n    at HomebridgeAPI.signalShutdown (/usr/local/lib/node_modules/homebridge/src/api.ts:279:10)\n    at BridgeService.teardown (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:571:14)\n    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:183:24)\n    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)\n    at process.emit (node:events:526:28)\n    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)","time":"2022-05-29T13:49:26.105Z","v":0}
```

**Comment by lenoxys** [comment]
Hello,

It may be related to the folder we store some data, I don't know where it does for Mac OS but on linux it's located here :

`/var/lib/homebridge/eufysecurity`

**Comment by jackattacck** [comment]
That is where I see the eufysecurity directory (users/$user/.homebridge/eufysecurity) but I’m not sure what is causing it to dump the accessories and re-add them upon a homebridge restart.

**Comment by thieren** [comment]
Hey @jackattacck 

I think this is not directly related to the plugin but more so to the homebridge instance and/or HomeKit caching. But just for good measure: can you try again with the latest beta. And also update your homebridge server to the latest version, please.

If this still is an issue enable debug mode for homebridge and try to find a hint in the logs as to where the accessories are (re-)added.

**Comment by jackattacck** [comment]
Sorry, I forgot to close this. A few updates ago, the problem was fixed. Al is good now. Thales!
