### ISSUE TITLE
[Bug]: Changing Eufy Base status crashes whole Homebridge

### ISSUE THREAD

**Issue by mariomaz87** [homebridge-eufy-security/plugin#518]
### What happened?

Since yesterday, changing the Eufy base status from Homekit crashes my whole Homebridge instance. It was working fine before.

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[02/22/2024, 08:57:55]  [EufySecurity]  INFO    Eufy Base Request to change station guard mode to: DISARM(3)
[2/22/2024, 8:57:56 AM] InvalidPropertyValueError: Invalid value for this property according to metadata
    at validValue (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/utils.ts:137:19)
    at Station.setGuardMode (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:692:19)
    at StationAccessory.handleSecuritySystemTargetStateSet (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:350:19)
    at setValue (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:99:33)
    at SecuritySystemTargetState.setHandler (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/BaseAccessory.ts:161:25)
    at SecuritySystemTargetState.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
[2/22/2024, 8:57:56 AM] Got SIGTERM, shutting down Homebridge...
[02/22/2024, 08:57:56]  [EufySecurity]  INFO    Finished shutdown!
[2/22/2024, 8:57:56 AM] Got SIGTERM, shutting down child bridge process...
[02/22/2024, 08:58:00]  [EufySecurity]  WARN    Eufy Base Changing guard mode to DISARM(3) did not complete. Retry...'
[2/22/2024, 8:58:00 AM] InvalidPropertyValueError: Invalid value for this property according to metadata
    at validValue (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/utils.ts:137:19)
    at Station.setGuardMode (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:692:19)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:359:21)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[2/22/2024, 8:58:01 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/22/2024, 8:58:06 AM] [HB Supervisor] Restarting Homebridge...
```

### config

```shell
{
    "username": "email",
    "password": "password",
    "country": "IT",
    "deviceName": "",
    "stations": [
        {
            "serialNumber": "serialnumber",
            "manualTriggerModes": [
                1,
                2
            ],
            "hkNight": 3,
            "hkHome": 1,
            "hkAway": 0
        }
    ],
    "ignoreDevices": [
        "serialnumber",
        "serialnumber",
        "serialnumber",
        "serialnumber"
    ],
    "platform": "EufySecurity",
    "ignoreStations": [],
    "cleanCache": true
}
```

**Comment by federicodigiacomo** [comment]
Thank you, I had the same problem with the S100 cameras. With your suggestion now the cameras work

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
