### ISSUE TITLE
[Bug]: Wifi Door Lock not working

### ISSUE THREAD

**Issue by nbhuta** [homebridge-eufy-security/plugin#527]
### What happened?

Unable to control the smart wifi lock from Eufy with the plugin, it worked once or twice then the response is timing out.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.6.x (Supported)

### NodeJS Version

v18 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Retreat
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Alfresco Main
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Games Room
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Retreat
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Upstairs Passage
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Laundry
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Entryway
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Games Room
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Manhole
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Alfresco Side
[Front Door@Front Door@Battery Level] Characteristic not in required or optional characteristic section for service LockMechanism. Adding anyway.
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Front Door
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Doorbell is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[03/20/2024, 04:19:11]  [EufySecurity]  INFO    Registering new accessory: Doorbell
[03/20/2024, 04:19:44]  [EufySecurity]  INFO    Looking for old cached accessories that seem to be outdated...
[03/20/2024, 04:19:44]  [EufySecurity]  INFO    No outdated cached accessories found.
[20/03/2024, 04:19:49] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:19:49] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:19:50] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:19:50] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:19:53] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:19:53] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:20:23] [Homebridge UI] [nbhuta] Accessory layout changes saved.
[20/03/2024, 04:20:33] [Homebridge UI] [nbhuta] Accessory layout changes saved.
[20/03/2024, 04:20:38] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:20:38] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:20:40] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:20:40] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:21:30] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:21:30] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:22:38] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:22:38] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:23:03] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:23:03] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:23:14] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:23:14] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:23:36] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:23:36] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:24:14] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:24:14] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:24:29] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:24:29] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/03/2024, 04:26:43] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Administrator Only Access': characteristic value expected boolean and received function. See https://homebridge.io/w/JtMGR for more info.
[20/03/2024, 04:26:43] [homebridge-eufy-security] Error: 
    at AdministratorOnlyAccess.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at AdministratorOnlyAccess.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2887:12)
    at AdministratorOnlyAccess.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### config

```shell
{
    "username": "*********@*******",
    "password": "********",
    "country": "AU",
    "deviceName": "",
    "platform": "EufySecurity",
    "stations": [
        {
            "hkAway": 0,
            "hkNight": 3,
            "serialNumber": "T8010P13203108C9",
            "hkHome": 63
        }
    ],
    "ignoreStations": [],
    "ignoreDevices": [
        "T8960P0020280085"
    ],
    "cleanCache": true,
    "cameras": [
        {
            "serialNumber": "T8960P0020280085",
            "rtsp": false,
            "talkback": false
        }
    ],
    "_bridge": {
        "username": "0E:6B:2D:AA:C4:1B",
        "port": 43821
    }
}
```

**Comment by nbhuta** [comment]
Yes

**Comment by lenoxys** [comment]
Hello what is the plug-in version used in your setup ?

Did you tried with the 2.3.14 ? (streaming issue has been reported but the rest works)

**Comment by nbhuta** [comment]
My version is v2.2.21

No updating now and will inform

**Comment by nbhuta** [comment]
Still the same unable to open or close the lock

**Comment by lenoxys** [comment]
can you provide logs ? see the wiki for the how to.

**Comment by nbhuta** [comment]
[22/03/2024, 10:50:24] [homebridge-eufy-security] Restarting child bridge...
[22/03/2024, 10:50:24] Got SIGTERM, shutting down child bridge process...
[03/22/2024, 10:50:24]  [EufySecurity]  INFO    Finished shutdown!
[22/03/2024, 10:50:29] [homebridge-eufy-security] Child bridge process ended
[22/03/2024, 10:50:29] [homebridge-eufy-security] Process Ended. Code: 143, Signal: null
[22/03/2024, 10:50:36] [homebridge-eufy-security] Restarting Process...
[22/03/2024, 10:50:37] [homebridge-eufy-security] Launched child bridge with PID 122911
[22/03/2024, 10:50:38] Registering platform 'homebridge-eufy-security.EufySecurity'
[22/03/2024, 10:50:38] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.3.14 child bridge successfully
[22/03/2024, 10:50:38] Loaded 15 cached accessories from cachedAccessories.0E6B2DAAC41B.
[03/22/2024, 10:50:38]  [EufySecurity]  WARN    warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[03/22/2024, 10:50:38]  [EufySecurity]  INFO    ffmpegPath set: /var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/ffmpeg-for-homebridge/ffmpeg
[03/22/2024, 10:50:38]  [EufySecurity]  INFO    Country set: AU
[03/22/2024, 10:50:38]  [EufySecurity]  INFO    Finished initializing!
[22/03/2024, 10:50:38] Publishing bridge accessory (name: homebridge-eufy-security, publishInfo: {
  username: '0E:6B:2D:AA:C4:1B',
  port: 43821,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[22/03/2024, 10:50:38] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-eufy-security) is running on port 43821.
[03/22/2024, 10:50:47]  [EufySecurity]  INFO    Updating existing accessory: NGRR_Base
[03/22/2024, 10:50:47]  [EufySecurity]  WARN    Front Door looks station but it's not could imply some errors! Type: 51
[03/22/2024, 10:50:47]  [EufySecurity]  INFO    Updating existing accessory: Front Door
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Living Room
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Retreat
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Alfresco Main
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Games Room
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Retreat
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Upstairs Passage
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Laundry
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Entryway
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Games Room
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Manhole
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Alfresco Side
[03/22/2024, 10:50:50]  [EufySecurity]  INFO    Updating existing accessory: Front Door
[03/22/2024, 10:50:51]  [EufySecurity]  INFO    Doorbell is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[03/22/2024, 10:50:51]  [EufySecurity]  INFO    WARNING: Motion detection and HomeKit Secure Video provide overlapping functionality. Only HomeKit Secure Video, when event recording is enabled in the Home app, will be used to trigger motion event notifications for this camera.
[03/22/2024, 10:51:01]  [EufySecurity]  ERROR   NGRR_Base handleSecuritySystemCurrentStateGets: Wrong return value
[03/22/2024, 10:51:01]  [EufySecurity]  ERROR   NGRR_Base handleSecuritySystemTargetStateGet: Wrong return value
[03/22/2024, 10:51:11]  [EufySecurity]  ERROR   NGRR_Base handleSecuritySystemCurrentStateGets: Wrong return value
[03/22/2024, 10:51:11]  [EufySecurity]  ERROR   NGRR_Base handleSecuritySystemTargetStateGet: Wrong return value
[03/22/2024, 10:51:26]  [EufySecurity]  INFO    Looking for old cached accessories that seem to be outdated...
[03/22/2024, 10:51:26]  [EufySecurity]  INFO    No outdated cached accessories found.

<img width="252" alt="image" src="https://github.com/homebridge-eufy-security/plugin/assets/125844818/ab6146d7-462e-4c0e-927f-b25ced958c30">

**Comment by lenoxys** [comment]
can you enable debug mode and redo the test ? see wiki for the how to enable debug

**Comment by nbhuta** [comment]
Sorry I am away from home, will do it today when I get back.

**Comment by lenoxys** [comment]
can you try with the latest version ?

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
