### ISSUE TITLE
[Bug]: 2.3.21 Boot Problem

### ISSUE THREAD

**Issue by TheBassfly** [homebridge-eufy-security/plugin#536]
### What happened?

After the update to V 2.3.21 I rann into a Boot Loop of the plugins Child bridge.

### Device Type

Doorbell (Supported)

### Plugin Version

v2.3.x (Best Effort)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Error: listen EADDRINUSE: address already in use :::49921
    at Server.setupListenHandle [as _listen2] (node:net:1897:16)
    at listenInCluster (node:net:1945:12)
    at Server.listen (node:net:2037:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
```

### config

```shell
{
    "enableDetailedLogging": false,
    "CameraMaxLivestreamDuration": 30,
    "pollingIntervalMinutes": 10,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "ignoreStations": [
        "T8030P2322510ACF",
        "T8410P4122298480"
    ],
    "ignoreDevices": [],
    "country": "DE",
    "cameras": [
        {
            "serialNumber": "T8114P0121091166",
            "rtsp": false,
            "snapshotHandlingMethod": 2,
            "videoConfig": {}
        },
        {
            "serialNumber": "T8410P4122298480",
            "rtsp": false,
            "videoConfig": {},
            "snapshotHandlingMethod": 2
        },
        {
            "serialNumber": "T8134P202326321C",
            "rtsp": false,
            "snapshotHandlingMethod": 2
        },
        {
            "serialNumber": "T8210P00202218E1",
            "rtsp": false,
            "enableCamera": true,
            "snapshotHandlingMethod": 2
        }
    ],
    "cleanCache": true,
    "unbridge": false,
    "ignoreMultipleDevicesWarning": true,
    "syncStationModes": false,
    "autoSyncStation": false,
    "username": ,
    "password": ,
    "deviceName": "",
    "platform": "EufySecurity",
    "_bridge": {
        "username": ,
        "port": 49921
    },
    "hsv": true
}
```

**Comment by lenoxys** [comment]
disable the plugin for 30min and try again. Sometimes homebase aren't closing their port.

**Comment by TheBassfly** [comment]
> disable the plugin for 30min and try again. Sometimes homebase aren't closing their port.

THX
I just solved it by changing the Port.
