### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by afalahi** [homebridge-eufy-security/plugin#58]
### What happened?

After updating to 2.0 I can't access the config UI due to this error
```console
[5/31/2022, 8:52:23 AM] [Homebridge UI] [homebridge-eufy-security] /homebridge/node_modules/homebridge-eufy-security/homebridge-ui/server.js:107
      this.config['country'] = body.country ??= 'US';
                                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
I noticed ` this.config['country'] = body.country ??= 'US'` in the server.js file in homebridge-ui dir

### Device Type

other (UnSupported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[5/31/2022, 8:52:23 AM] [Homebridge UI] [homebridge-eufy-security] /homebridge/node_modules/homebridge-eufy-security/homebridge-ui/server.js:107
      this.config['country'] = body.country ??= 'US';
                                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by afalahi** [comment]
Issue fixed by updating to node16
