### ISSUE TITLE
[Bug]: unable to add eufy Homebase 2 

### ISSUE THREAD

**Issue by megonooja** [homebridge-eufy-security/plugin#587]
### What happened?

Unable to add my home base 2 where receiving error in attached screen “login was not successful”
![IMG_4477](https://github.com/homebridge-eufy-security/plugin/assets/98545297/3601ecd8-2fb8-4b55-9341-854502cac334)

### Device Type

Doorbell (Supported)

### Plugin Version

v3.0.x (Best Effort)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[25/06/2024, 09:08:40] [EufySecurity] Initializing EufySecurity platform...
[25/06/2024, 09:09:58] [EufySecurity] Initializing EufySecurity platform...
[25/06/2024, 09:09:58] [EufySecurity] Initializing child bridge 0E:BC:4F:A4:16:CF
[25/06/2024, 09:10:03] [EufySecurity] Launched child bridge with PID 25720
[25/06/2024, 09:10:09] [EufySecurity] Loaded homebridge-eufy-security v3.4.2 child bridge successfully
[25/06/2024, 09:10:10] Homebridge v1.8.3 (HAP v0.12.2) (EufySecurity) is running on port 34663.
[25/06/2024, 11:10:27] [EufySecurity] Initializing EufySecurity platform...
[25/06/2024, 11:10:27] [EufySecurity] Initializing child bridge 0E:BC:4F:A4:16:CF
[25/06/2024, 11:10:33] [EufySecurity] Launched child bridge with PID 28245
[25/06/2024, 11:10:39] [EufySecurity] Loaded homebridge-eufy-security v3.4.2 child bridge successfully
[25/06/2024, 11:10:39] Loaded 0 cached accessories from cachedAccessories.0EBC4FA416CF.
[25/06/2024, 11:10:40] Homebridge v1.8.3 (HAP v0.12.2) (EufySecurity) is running on port 34663.
[25/06/2024, 13:27:10] [EufySecurity] Initializing EufySecurity platform...
[25/06/2024, 13:27:10] [EufySecurity] Initializing child bridge 0E:BC:4F:A4:16:CF
[25/06/2024, 13:27:15] [EufySecurity] Launched child bridge with PID 31188
[25/06/2024, 13:27:21] [EufySecurity] Loaded homebridge-eufy-security v3.4.2 child bridge successfully
[25/06/2024, 13:27:21] Loaded 0 cached accessories from cachedAccessories.0EBC4FA416CF.
[25/06/2024, 13:27:22] Homebridge v1.8.3 (HAP v0.12.2) (EufySecurity) is running on port 34663.
[25/06/2024, 13:29:46] [EufySecurity] Restarting child bridge...
[25/06/2024, 13:29:46] Got SIGTERM, shutting down child bridge process...
[06/25/2024, 13:29:47]	[EufySecurity]	INFO	Finished shutdown!
[25/06/2024, 13:29:52] [EufySecurity] Child bridge process ended
[25/06/2024, 13:29:52] [EufySecurity] Process Ended. Code: 143, Signal: null
[25/06/2024, 13:30:30] [EufySecurity] Initializing EufySecurity platform...
```

### config

```shell
[06/25/2024, 13:31:25]	[EufySecurity]	INFO	No outdated cached accessories found.
[25/06/2024, 13:34:48] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 13:34:58] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:109]	Using bropats eufy-security-client library in version 3.0.0
[25/06/2024, 13:34:58] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[25/06/2024, 13:34:58] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	WARN	[server.js:217]	Stored accessories file does not exist.
[25/06/2024, 13:34:58] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[25/06/2024, 13:34:58] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	WARN	[server.js:217]	Stored accessories file does not exist.
[25/06/2024, 13:34:58] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /nodeJSVersion
[25/06/2024, 13:35:22] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 13:35:28] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:109]	Using bropats eufy-security-client library in version 3.0.0
[25/06/2024, 13:35:28] [Homebridge UI] [homebridge-eufy-security] node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at target._send (node:internal/child_process:865:20)
    at target.send (node:internal/child_process:738:19)
    at UiServer.ready (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/@homebridge/plugin-ui-utils/dist/server.js:105:17)
    at new UiServer (/var/lib/homebridge/node_modules/homebridge-eufy-security/homebridge-ui/server.js:66:14)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-eufy-security/homebridge-ui/server.js:426:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on process instance at:
    at node:internal/child_process:869:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.12.1
[25/06/2024, 13:39:23] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 13:39:29] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:109]	Using bropats eufy-security-client library in version 3.0.0
[25/06/2024, 13:49:22] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 13:49:27] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:109]	Using bropats eufy-security-client library in version 3.0.0
[25/06/2024, 13:49:27] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[25/06/2024, 13:49:27] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	WARN	[server.js:217]	Stored accessories file does not exist.
[25/06/2024, 13:49:27] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[25/06/2024, 13:49:27] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	WARN	[server.js:217]	Stored accessories file does not exist.
[25/06/2024, 13:49:27] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /nodeJSVersion
[25/06/2024, 13:49:50] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[25/06/2024, 13:49:50] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	INFO	[server.js:140]	deleting persistent.json due to new login
[25/06/2024, 13:49:50] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:149]	init eufyClient
[25/06/2024, 13:49:53] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:168]	login with credentials
[25/06/2024, 13:49:53] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:172]	connected?: false
[25/06/2024, 13:50:03] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[25/06/2024, 13:50:16] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:51:07] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 13:52:08] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[25/06/2024, 13:52:08] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	WARN	[server.js:217]	Stored accessories file does not exist.
[25/06/2024, 13:52:08] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /nodeJSVersion
[25/06/2024, 13:55:38] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 14:29:13] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 14:29:52] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 14:31:07] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 14:31:48] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:109]	Using bropats eufy-security-client library in version 3.0.0
[25/06/2024, 14:31:48] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[25/06/2024, 14:31:48] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	WARN	[server.js:217]	Stored accessories file does not exist.
[25/06/2024, 14:31:48] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[25/06/2024, 14:31:48] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	WARN	[server.js:217]	Stored accessories file does not exist.
[25/06/2024, 14:31:48] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /nodeJSVersion
[25/06/2024, 14:32:17] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[25/06/2024, 14:32:17] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	INFO	[server.js:140]	deleting persistent.json due to new login
[25/06/2024, 14:32:17] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:145]	Could not delete persistent.json due to error: Error: ENOENT: no such file or directory, unlink '/var/lib/homebridge/eufysecurity/persistent.json'
[25/06/2024, 14:32:17] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:149]	init eufyClient
[25/06/2024, 14:32:20] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:168]	login with credentials
[25/06/2024, 14:32:20] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	DEBUG	[server.js:172]	connected?: false
[25/06/2024, 14:32:31] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[25/06/2024, 14:32:42] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /login
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:33:22] [Homebridge UI] [homebridge-eufy-security] [3.4.2]	ERROR	[server.js:250]	
      #########################
      ######### ERROR #########
      #########################
      You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
      #########################
[25/06/2024, 14:34:18] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[25/06/2024, 14:34:19] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
```

**Comment by lenoxys** [comment]
You're not using a guest admin account with this plugin! You must use a guest admin account!
      Please look here for more details: 
      https://github.com/homebridge-eufy-security/plugin/wiki/Create-a-dedicated-admin-account-for-Homebridge-Eufy-Security-Plugin
