### ISSUE TITLE
[Bug]: 2.0 Continuous Crash

### ISSUE THREAD

**Issue by gmogoody** [homebridge-eufy-security/plugin#62]
### What happened?

Upgraded to 2.0 when released. Has been fine up until today. Noticed my Homebase2s were not responding in HomeKit. Launched Homebridge and saw plugin was continuously crashing now as a child bridge. 

### Device Type

Station (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[6/1/2022, 7:36:04 PM] [homebridge-eufy-security] Restarting Process...
[6/1/2022, 7:36:05 PM] [homebridge-eufy-security] Launched child bridge with PID 7540
[6/1/2022, 7:36:05 PM] Registering platform 'homebridge-eufy-security.EufySecurity'
[6/1/2022, 7:36:05 PM] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.0.0 child bridge successfully
[6/1/2022, 7:36:05 PM] Loaded 2 cached accessories from cachedAccessories.0E4AC36F389B.
[6/1/2022, 7:36:05 PM] [EufySecurity-2.0.0] WARN:  warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[6/1/2022, 7:36:05 PM] [EufySecurity-2.0.0] ERROR: Error cleaning config: Error: EACCES: permission denied, open '/homebridge/config.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at EufySecurityPlatform.clean_config (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:519:10)
    at new EufySecurityPlatform (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:110:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:134:42) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/homebridge/config.json'
}
[6/1/2022, 7:36:05 PM] [EufySecurity-2.0.0] INFO:  Country set: US
[6/1/2022, 7:36:05 PM] [EufySecurity-2.0.0] INFO:  Finished initializing!
[6/1/2022, 7:36:05 PM] Homebridge v1.4.1 (HAP v0.10.2) (homebridge-eufy-security) is running on port 46605.
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Function.from (node:buffer:323:9)
    at stringWithLength (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/utils.ts:27:35)
    at p2pDidToBuffer (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/utils.ts:55:18)
    at buildLookupWithKeyPayload (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/utils.ts:60:26)
    at P2PClientProtocol.lookupByAddress (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:304:50)
    at /homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:284:51
    at Array.map (<anonymous>)
    at P2PClientProtocol.lookup (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:284:29)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:361:26)
[6/1/2022, 7:36:07 PM] [homebridge-eufy-security] Child bridge process ended
[6/1/2022, 7:36:07 PM] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
[6/1/2022, 7:36:14 PM] [homebridge-eufy-security] Restarting Process...
```

**Comment by gmogoody** [comment]
I think I know what happened. My Smart Lock also stopped responding today and I think it is dead. The plugin was trying to get status unsuccessfully causing it to crash. 

Removing the dead lock solved my continuous reboot.
