### ISSUE TITLE
[Bug]: Issue when manually disable the alarm trigger

### ISSUE THREAD

**Issue by Stefvgl89** [homebridge-eufy-security/plugin#651]
### What happened?

A bug happened!
When triggering an alarm, everything works correctly, keeping into account the state of the alarm (home, away, ...).
When trying to disarm (trigger: false) the alarm, the following error occurs (+ the alarm sound goes off):
TypeError: Cannot read properties of undefined (reading 'then')
    at StationAccessory.handleManualTriggerSwitchStateSet (/var/lib/homebridge/node_modules/homebridge-eufy-security/dist/accessories/StationAccessory.js:331:17)
    at setValue (/var/lib/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:123:33)
    at On.setHandler (/var/lib/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/BaseAccessory.ts:177:25)
    at On.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2552:42)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:196:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:177:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:170:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:16)
    at On.Characteristic.handleSetRequest (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:875:24)

Immediately after this, following error occurs:
Got SIGTERM, shutting down Homebridge...

And Homebridge is being restarted.

I tried different versions of both homebridge and the plugin. Error remains the same.

### Device Type

Station (Supported)

### Plugin Version

other (UnSupported)

### HomeBridge Version

v1.7.x (Supported)

### NodeJS Version

v20 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:145]  Garage REGISTER CHARACTERISTIC SecuritySystem / SecuritySystemCurrentState / undefined
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:150]  Garage REGISTER CHARACTERISTIC (0000007E-0000-1000-8000-0026BB765291) / (00000066-0000-1000-8000-0026BB765291)
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:190]  Garage ON 'SecuritySystem / SecuritySystemCurrentState'
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:145]  Garage REGISTER CHARACTERISTIC SecuritySystem / SecuritySystemTargetState / undefined
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:150]  Garage REGISTER CHARACTERISTIC (0000007E-0000-1000-8000-0026BB765291) / (00000067-0000-1000-8000-0026BB765291)
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:190]  Garage ON 'SecuritySystem / SecuritySystemTargetState'
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:145]  Garage REGISTER CHARACTERISTIC Switch / On / STATION Garage Siren
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    DEBUG   [BaseAccessory.ts:150]  Garage REGISTER CHARACTERISTIC (00000049-0000-1000-8000-0026BB765291) / (00000025-0000-1000-8000-0026BB765291)
[11/26/2024 18:03:41]   [EufySecurity-4.3.0]    INFO    [platform.ts:553]       Updating existing accessory: STATION Garage
[11/26/2024 18:03:56]   [EufySecurity-4.3.0]    INFO    [StationAccessory.ts:393]       Garage tried to trigger alarm, but the current station mode prevents the alarm from being triggered. Please look in in the configuration if you want to change this behaviour.
[11/26/2024, 6:04:02 PM] TypeError: Cannot read properties of undefined (reading 'then')
    at StationAccessory.handleManualTriggerSwitchStateSet (/var/lib/homebridge/node_modules/homebridge-eufy-security/dist/accessories/StationAccessory.js:331:17)
    at setValue (/var/lib/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/StationAccessory.ts:123:33)
    at On.setHandler (/var/lib/homebridge/node_modules/homebridge-eufy-security/src/plugin/accessories/BaseAccessory.ts:177:25)
    at On.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:196:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:177:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:170:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:16)
    at On.Characteristic.handleSetRequest (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:871:24)
[11/26/2024, 6:04:02 PM] Got SIGTERM, shutting down Homebridge...
[11/26/2024 18:04:02]   [EufySecurity-4.3.0]    DEBUG   [platform.ts:386]       Push Closed!
[11/26/2024 18:04:02]   [EufySecurity-4.3.0]    DEBUG   [platform.ts:392]       Closed!
[11/26/2024 18:04:02]   [EufySecurity-4.3.0]    INFO    [platform.ts:658]       Finished shutdown!
```

### config

```shell
{
            "platform": "EufySecurity",
            "name": "EufySecurity",
            "deviceName": "",
            "enableDetailedLogging": true,
            "omitLogFiles": false,
            "CameraMaxLivestreamDuration": 60,
            "pollingIntervalMinutes": 10,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "ignoreStations": [],
            "ignoreDevices": [
                "T8160P21523207B",
                "T8160P215232207",
                "T8410P415243A73"
            ],
            "country": "BE",
            "stations": [
                {
                    "serialNumber": "T8410P412243A73",
                    "manualTriggerModes": [
                        2
                    ]
                },
                {
                    "serialNumber": "T8030P232491008",
                    "manualTriggerModes": [
                        2,
                        0,
                        1,
                        3
                    ]
                }
            ],
            "cameras": [],
            "cleanCache": true,
            "ignoreMultipleDevicesWarning": false,
            "autoSyncStation": false
        }
    ],
    "disabledPlugins": [
        "homebridge-ring"
    ]
}
```

**Comment by lenoxys** [comment]
**Thank you for taking the time to report this issue.**

As part of a repository cleanup, we are closing issues that have been open for more than 12 months without resolution. A **beta version** of the plugin has been released that includes significant changes and improvements.

We encourage you to try the latest beta and see if your issue has been addressed. If the problem persists, please feel free to open a new issue with updated details and logs from the latest version.

Thank you for your patience and support!
