### ISSUE TITLE
[Bug]: latest beta V1.1.1-beta.51 setup works but Homebridge crashes

### ISSUE THREAD

**Issue by T18DJ** [homebridge-eufy-security/plugin#7]
### What happened?

A bug happened!

I tried removing the persistent.json in the eufysecurity folder, however this didn't solve it.

Could you support?

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[11/04/2022, 22:45:37] [EufySecurity] Initializing EufySecurity platform...
[11/04/2022, 22:45:37] [EufySecurity] warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[11/04/2022, 22:45:37] [EufySecurity] Country set: NL
[11/04/2022, 22:45:37] Error: EEXIST: file already exists, copyfile '/var/lib/homebridge/persistent.json' -> '/var/lib/homebridge/eufysecurity/persistent.json'
    at Object.copyFileSync (node:fs:2800:3)
    at new EufySecurityPlatform (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:138:10)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[11/04/2022, 22:45:37] Got SIGTERM, shutting down Homebridge...
```

**Comment by jordainfg** [comment]
Hi, I'm getting this as well, did you find a solution?

**Comment by T18DJ** [comment]
> Hi, I'm getting this as well, did you find a solution? I'm also setting it up in NL
> 
> @T18DJ

Hey! I reinstalled the last stable version and then created this ticket. Hopefully the creator can use the feedback and solve the issue for this great plugin!

**Comment by lenoxys** [comment]
Hello

Ok I see until I provide a fix you can remove the file manually through SSH.

'''sudo rm -rf /var/lib/homebridge/persistent.json'''

**Comment by lenoxys** [comment]
should be good with .52

**Comment by T18DJ** [comment]
Solved!
