### ISSUE TITLE
[Bug]: [homebridge-eufy-security] [1.0.8] DEBUG: Captcha verification received

### ISSUE THREAD

**Issue by gintonic4all** [homebridge-eufy-security/plugin#8]
### What happened?

I just wanted to re-setup my eufy security for migration to another raspi-device. 

Because I could not remember my password, I reset it via the eufy website. When (re)logging in again in the eufy app not only the password is required - also a captcha code is presented and asked to be entered. Here: no problems following the procedure (that seems to be new to me).
   
Now in the homebridge eufy-security package the setup wizzard stops after having entered user-name and password. I have the 2FA-option set in the eufy app. And the protocol says "[homebridge-eufy-security] [1.0.8] DEBUG: Captcha verification received"...

Seems the (new?) log-in method needs to be implemented in the package, isn't it?

Best regards, 
gintonic4all

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[15/04/2022, 17:57:57] [Homebridge UI] [homebridge-eufy-security] [1.0.8] INFO:  Switching to another API_BASE (https://security-app-eu.eufylife.com) and get new token.
[15/04/2022, 17:57:57] [Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Renew token
[15/04/2022, 17:57:57] [Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Authenticate and get an access token { token: null, tokenExpiration: null }
[15/04/2022, 17:57:57] [Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Request: {
  method: 'post',
  endpoint: 'v2/passport/login',
  baseUrl: 'https://security-app-eu.eufylife.com',
  token: null,
  data: {
    client_secret_info: {
      public_key: '043631b4e5bc7520bd0f105dd93e649899517acbc98784e52d7188892a0775ee4f0f3faa32746d6e1e0d0c6c098f025a1043c6182097f5905d9cd272ae9b23f126'
    },
    enc: 0,
    email: 'xxx@yyy.com', // I have deleted my e-mail adress here 
    password: 'w1YqWTaiHoMefbqSt4fywQ==', //this one is not my real pw... it's from the log
    time_zone: 7200000,
    transaction: '1650038277236'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'US',
    language: 'en',
    openudid: '1ae3d784aa54bc01',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: 'd5127e10d030',
    Model_type: 'PHONE',
    timezone: 'GMT+02:00',
    'Cache-Control': 'no-cache',
    gtoken: '4f6749e34ef5d4c5a6515070e6cb1bf2'
  }
}
[15/04/2022, 17:57:57] [Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Response: {
  code: 100032,
  msg: 'Failed to request.',
  data: {
    captcha_id: '924ecf25-acf2-4016-b730-fc2882ecde29',
    item: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAArCAIAAACGv1O8AAAJTklEQVR4nOxafUxbVf+/7aW97daX2/VttIFKXxWl1cyaImnngm/TJYvGVawuLmqWmRCzf/xDw3yJzMXMGV8SM2WwaAhKNYpRoySCEMDKiwiYEkohKaWUtraFvre39/b+8vM+T1Nb2t75PNPlYZ+/yDnnc77nc873+z3fe0oNjuPALgb1n17AP4zr+nc3ruvf3biuf3fjuv7djWtdP4ZhV7VCrbl6UwMAgKIoCIIUCuWKWBiGeb3eubk5t9vNYrEOHz4sEon+2gL8fj8MwxAElRtQRX80GqXRaEwm84qsIggSCoUikYjP59vc3ERR9NChQ2KxGARBKrWKx2EYNj4+/vHHH8/MzGxsbITD4a6urhMnToAgSNJ6LpeLRCKZTMbj8Vy8ePHxxx83Go01NWWU4mWQy+WcTudzzz03MDCQTCYrOGER0W63v/nmmw888IBYLAYAgMFgyOVynU73yiuvzM3NJRKJchYJuN3uo0eP0ul0AACEQmFLS4vNZkMQpDKraIYLFy6Yzeba2loAANra2ubn58sNLqsfx/Hz588LhcJDhw79/PPPFYaRPJaqO05s+vnz50UiEYfDaW9vn5mZQVGUnOr/h9frfeONN/h8fqG5xsbG7u7ucpRK3igSiWAYXltb++WXX0jq8Xg8J0+epFAozc3NX3/99cLCwo8//tjf33/27NmGhgYmk3n48GHKTiCmSqVSDocjFArp9XqLxaLT6ci7fTKZ/Pbbb3t6esLhsFKpfPTRR81mM4PB8Hq9LperHKtS/Ot0uvr6+qmpqenp6dLeUCi0d+9eCIIK0xsEQQ0NDUTmu/vuuxkMBrFB8XjcYDC0trZ+9913NptNr9fvKGxjYwNBEBAEVSqVVqstG7QlwHHc6XT29PQ4nU6JRPLiiy8aDAYOh9PQ0DA/P9/S0oKi6M6zVXAnBEGOHz8OgqDBYAiHw4Vdv//++9tvv/3RRx+5XK7C9mw2+8UXXwAAwGKxYrFY0WwHDhwAAKC7uzsej+9ocXl52Ww2c7nc06dPFxIrLDKPU6dOQRAklUq/+uqrPAVFUY/HU7SSQlB39EYCNBpNrVYLhcJkMvnbb7/ltywej1+6dOnMmTPd3d1ut/tP7lRTs2/fPo1GA4LgzMxMYdf29rZSqaTT6T6fr9yFxOPx4vF4JpMJhUKjo6P9/f1dXV0jIyMIglQ+/9HR0YmJCQqF8uCDDxoMBhqNRrSDICiVSlksVjlilfcvQn80GrXb7SaTiXDshYWFvr6+ZDLJ4/FkMlkRhc1mKxSKQCCwsLBw11135dtdLtf6+jqXy4UgaEdXRBAERdFQKIQgiM1mW11d9fl8fr8/l8tNTEzodLpyd2c8Hp+dnbXb7XV1da2trQKBoPJmFaLKbaxWq2EY3t7eXlpayhuzWq0Oh4NGo1ksFqlUWkSBYbi+vh7DMIfDQbTgOO73+z/99FObzcbj8Qo3JT/g0qVLBw8elMlkk5OTuVxuZWVlenp6a2sLhuH777+fyWRWKKJisdjQ0BCO42KxuLW1tWqJkQeFQqmSYBobG2EYjkajLpcrEomw2eyJiYlvvvkGRdETJ04YjcbSNCYQCEQiUTKZXF1dJdKk3W7//PPPrVYrCIJHjhxRKpVFFBRFJycnZ2dnEQRhMpnpdFqlUrW1td1zzz0qlYqoIypga2uLOJ5jx47lPZ8kquin0+lqtfqnn34Kh8NLS0u1tbUffPDB+vq6Xq9/6qmniAKjCJx/w+FwtLe3oyi6uLg4Pz+fSqUeeeSRU6dOcTicUtZjjz2m1Wr5fP74+Pjly5fr6+vvu+++O++8k4yGqakpBEHEYnFtbe2Ok5cDjuPVL5jGxkYulxsMBsfGxiKRyNDQEIVCUSqVBoOhHGXfvn0CgcDlcl2+fDmbzcIwfMsttzz88MNPP/00DMOl42k0WktLy+23385kMtlsdm9vbzAYTKVSZDRgGJbNZgOBgEKhUKvVZCiFqK5fq9XCMOx0Ont7e5eXl1OpFJVKHR4e7unpeeKJJ3b8NJBIJBwOh0qlSiQSmUx22223GY1GvV7P5XLLWYH+AAAAKpUKBEGfz5dMJskIyGazCIIQ1b5GoyFDKUR1/U1NTVwuNx6POxyOdDotl8uz2azP53v++eej0ehDDz10ww03FKUchULBZDJpNNqxY8def/31K1pQXv/W1lY+51W4pBgMht/v5/P5EonEbrc3NzeXjgkEAmNjY2w2+9577y3qqp4qIQjSaDRsNjudTtfV1XV2dr788ssmkymRSJw9e/bChQtF9zwAAEqlksVipdNpDMMikQg54f8CUfyBIPjkk0/mGyt/Qe/fv7+mpiaXy+1Y52az2cHBwZdeeun06dOldQSpq+Kmm26CIEgsFre3t5vNZovFcubMGYvFkkgk+vr6zp07Nzs7W0RRq9UsFsv7B8iYKOKSr3wBADhw4AAIgl6vt7BII5DL5b788ssXXnhhaWlJqVR6PJ5iMpnScmRkRCAQ7N+//7333svXuW63+/jx40TQHjx4MBgM5nK5PKWrq6uurs5kMv3www9kTBSis7Nz7969V7ROk8lEp9PlcvnIyEg0GsVxHMOwtbW1ixcv3nzzzVQqtamp6bPPPiv9miSlP5lMli7oL6OquU8++YTNZhMfCyQpH374IVEgGo3G1157zWq1Dg4OdnR03HrrrTQaTSgUdnZ2BoPBUiIp/TiOG41GAABOnjy5srJS2L6ysvLOO++8+uqri4uLhe2JROKOO+4AAODcuXOZTIakFQKTk5MMBkMmkw0MDJCkeDyed999l6hH2Gy2SqXas2cPkTjkcvlbb71FPOGUgpR+DMM6OjrodPqRI0d+/fXXot5YLOb1ektd69lnn+XxeB0dHYFAgKQM4glkY2ODQqFAEPT999+TJyYSiby/EFGpUCieeeaZ4eHhCixSaYZKpR49enR7e/vGG29samoq6mX9gVJWW1ubVqttbm4WCoXko4NCoeA4rtFoYrEYn8/HMIzkE8iePXvS6TSDwbBarbFYTCqVEpdiFevkj2Vzc9Pr9ZI/EBRF4/F4Op0mTyGQyWTef//9K11hkWmSQUe5Nv//g/CC0r//67jWf/+42iiOfzIl5/8S/uRaRWXmP7sFf89JXN3fv/4T/D27v9vj/0/6C7d8l8R/sf/vEtl57Hb//78AAAD//0bqA8HMSrLbAAAAAElFTkSuQmCC'
  }
}
[15/04/2022, 17:57:57] [Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Captcha verification received {
  captchaId: '924ecf25-acf2-4016-b730-fc2882ecde29',
  item: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAArCAIAAACGv1O8AAAJTklEQVR4nOxafUxbVf+/7aW97daX2/VttIFKXxWl1cyaImnngm/TJYvGVawuLmqWmRCzf/xDw3yJzMXMGV8SM2WwaAhKNYpRoySCEMDKiwiYEkohKaWUtraFvre39/b+8vM+T1Nb2t75PNPlYZ+/yDnnc77nc873+z3fe0oNjuPALgb1n17AP4zr+nc3ruvf3biuf3fjuv7djWtdP4ZhV7VCrbl6UwMAgKIoCIIUCuWKWBiGeb3eubk5t9vNYrEOHz4sEon+2gL8fj8MwxAElRtQRX80GqXRaEwm84qsIggSCoUikYjP59vc3ERR9NChQ2KxGARBKrWKx2EYNj4+/vHHH8/MzGxsbITD4a6urhMnToAgSNJ6LpeLRCKZTMbj8Vy8ePHxxx83Go01NWWU4mWQy+WcTudzzz03MDCQTCYrOGER0W63v/nmmw888IBYLAYAgMFgyOVynU73yiuvzM3NJRKJchYJuN3uo0eP0ul0AACEQmFLS4vNZkMQpDKraIYLFy6Yzeba2loAANra2ubn58sNLqsfx/Hz588LhcJDhw79/PPPFYaRPJaqO05s+vnz50UiEYfDaW9vn5mZQVGUnOr/h9frfeONN/h8fqG5xsbG7u7ucpRK3igSiWAYXltb++WXX0jq8Xg8J0+epFAozc3NX3/99cLCwo8//tjf33/27NmGhgYmk3n48GHKTiCmSqVSDocjFArp9XqLxaLT6ci7fTKZ/Pbbb3t6esLhsFKpfPTRR81mM4PB8Hq9LperHKtS/Ot0uvr6+qmpqenp6dLeUCi0d+9eCIIK0xsEQQ0NDUTmu/vuuxkMBrFB8XjcYDC0trZ+9913NptNr9fvKGxjYwNBEBAEVSqVVqstG7QlwHHc6XT29PQ4nU6JRPLiiy8aDAYOh9PQ0DA/P9/S0oKi6M6zVXAnBEGOHz8OgqDBYAiHw4Vdv//++9tvv/3RRx+5XK7C9mw2+8UXXwAAwGKxYrFY0WwHDhwAAKC7uzsej+9ocXl52Ww2c7nc06dPFxIrLDKPU6dOQRAklUq/+uqrPAVFUY/HU7SSQlB39EYCNBpNrVYLhcJkMvnbb7/ltywej1+6dOnMmTPd3d1ut/tP7lRTs2/fPo1GA4LgzMxMYdf29rZSqaTT6T6fr9yFxOPx4vF4JpMJhUKjo6P9/f1dXV0jIyMIglQ+/9HR0YmJCQqF8uCDDxoMBhqNRrSDICiVSlksVjlilfcvQn80GrXb7SaTiXDshYWFvr6+ZDLJ4/FkMlkRhc1mKxSKQCCwsLBw11135dtdLtf6+jqXy4UgaEdXRBAERdFQKIQgiM1mW11d9fl8fr8/l8tNTEzodLpyd2c8Hp+dnbXb7XV1da2trQKBoPJmFaLKbaxWq2EY3t7eXlpayhuzWq0Oh4NGo1ksFqlUWkSBYbi+vh7DMIfDQbTgOO73+z/99FObzcbj8Qo3JT/g0qVLBw8elMlkk5OTuVxuZWVlenp6a2sLhuH777+fyWRWKKJisdjQ0BCO42KxuLW1tWqJkQeFQqmSYBobG2EYjkajLpcrEomw2eyJiYlvvvkGRdETJ04YjcbSNCYQCEQiUTKZXF1dJdKk3W7//PPPrVYrCIJHjhxRKpVFFBRFJycnZ2dnEQRhMpnpdFqlUrW1td1zzz0qlYqoIypga2uLOJ5jx47lPZ8kquin0+lqtfqnn34Kh8NLS0u1tbUffPDB+vq6Xq9/6qmniAKjCJx/w+FwtLe3oyi6uLg4Pz+fSqUeeeSRU6dOcTicUtZjjz2m1Wr5fP74+Pjly5fr6+vvu+++O++8k4yGqakpBEHEYnFtbe2Ok5cDjuPVL5jGxkYulxsMBsfGxiKRyNDQEIVCUSqVBoOhHGXfvn0CgcDlcl2+fDmbzcIwfMsttzz88MNPP/00DMOl42k0WktLy+23385kMtlsdm9vbzAYTKVSZDRgGJbNZgOBgEKhUKvVZCiFqK5fq9XCMOx0Ont7e5eXl1OpFJVKHR4e7unpeeKJJ3b8NJBIJBwOh0qlSiQSmUx22223GY1GvV7P5XLLWYH+AAAAKpUKBEGfz5dMJskIyGazCIIQ1b5GoyFDKUR1/U1NTVwuNx6POxyOdDotl8uz2azP53v++eej0ehDDz10ww03FKUchULBZDJpNNqxY8def/31K1pQXv/W1lY+51W4pBgMht/v5/P5EonEbrc3NzeXjgkEAmNjY2w2+9577y3qqp4qIQjSaDRsNjudTtfV1XV2dr788ssmkymRSJw9e/bChQtF9zwAAEqlksVipdNpDMMikQg54f8CUfyBIPjkk0/mGyt/Qe/fv7+mpiaXy+1Y52az2cHBwZdeeun06dOldQSpq+Kmm26CIEgsFre3t5vNZovFcubMGYvFkkgk+vr6zp07Nzs7W0RRq9UsFsv7B8iYKOKSr3wBADhw4AAIgl6vt7BII5DL5b788ssXXnhhaWlJqVR6PJ5iMpnScmRkRCAQ7N+//7333svXuW63+/jx40TQHjx4MBgM5nK5PKWrq6uurs5kMv3www9kTBSis7Nz7969V7ROk8lEp9PlcvnIyEg0GsVxHMOwtbW1ixcv3nzzzVQqtamp6bPPPiv9miSlP5lMli7oL6OquU8++YTNZhMfCyQpH374IVEgGo3G1157zWq1Dg4OdnR03HrrrTQaTSgUdnZ2BoPBUiIp/TiOG41GAABOnjy5srJS2L6ysvLOO++8+uqri4uLhe2JROKOO+4AAODcuXOZTIakFQKTk5MMBkMmkw0MDJCkeDyed999l6hH2Gy2SqXas2cPkTjkcvlbb71FPOGUgpR+DMM6OjrodPqRI0d+/fXXot5YLOb1ektd69lnn+XxeB0dHYFAgKQM4glkY2ODQqFAEPT999+TJyYSiby/EFGpUCieeeaZ4eHhCixSaYZKpR49enR7e/vGG29samoq6mX9gVJWW1ubVqttbm4WCoXko4NCoeA4rtFoYrEYn8/HMIzkE8iePXvS6TSDwbBarbFYTCqVEpdiFevkj2Vzc9Pr9ZI/EBRF4/F4Op0mTyGQyWTef//9K11hkWmSQUe5Nv//g/CC0r//67jWf/+42iiOfzIl5/8S/uRaRWXmP7sFf89JXN3fv/4T/D27v9vj/0/6C7d8l8R/sf/vEtl57Hb//78AAAD//0bqA8HMSrLbAAAAAElFTkSuQmCC'
}
```

**Comment by lenoxys** [comment]
Hello you will need to use the beta unfortunately

**Comment by gintonic4all** [comment]
> Hello you will need to use the beta unfortunately

Hi, just tried the beta. Unfortunately the status log shows something's wrong when I restart homebridge after configuration of the EufySecurity plugin:

[15/04/2022, 22:51:30] [EufySecurity] Initializing EufySecurity platform...
[15/04/2022, 22:51:30] [EufySecurity] warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[15/04/2022, 22:51:30] [EufySecurity] Country set: DE
[15/04/2022, 22:51:30] Error: EEXIST: file already exists, copyfile '/var/lib/homebridge/persistent.json' -> '/var/lib/homebridge/eufysecurity/persistent.json'
    at Object.copyFileSync (node:fs:2804:3)
    at new EufySecurityPlatform (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:138:10)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)

**Comment by lenoxys** [comment]
Duplicate #7 ; should be good with .52

**Comment by lenoxys** [comment]
Looks good ! Closing this case
